/* ─────────────────────────────────────────────────────
   CONSTANTS.JS — 디자인 토큰, 카테고리, 헬퍼, 단어장
───────────────────────────────────────────────────── */

// ── Design Tokens ──────────────────────────────────
export const T = {
  bg:        "#F7F4EF",
  bgCard:    "#FFFFFF",
  bgSub:     "#F0EDE7",
  border:    "#E4DDD3",
  borderMid: "#CEC5B8",
  text:      "#2C2825",
  textSub:   "#8C8077",
  textMute:  "#B8AFA5",
  accent:    "#6B7C3A",
};

// ── Categories ─────────────────────────────────────
export const CATS = [
  { id:"schedule", label:"일정",    icon:"o", color:"#C0443A", bg:"#FDECEA", text:"#9B2E25" },
  { id:"event",    label:"이벤트",  icon:"o", color:"#B09520", bg:"#FBF8E3", text:"#7A6A10" },
  { id:"archive",  label:"아카이브", icon:"o", color:"#4A8A5A", bg:"#EBF5EE", text:"#2E6640" },
];

export const HEALTH_SUBS = [
  { id:"weight",          label:"체중" },
  { id:"diet",            label:"식단" },
  { id:"weight_training", label:"웨이트" },
  { id:"cardio",          label:"카디오" },
];

export const REVIEW_SUBS = [
  { id:"book",   label:"책" },
  { id:"wine",   label:"와인" },
  { id:"coffee", label:"커피" },
];

export const WEIGHT_FETCH_DAYS = 30; // 체중 그래프 조회 일수

// 아카이브 서브카테고리 ID 목록 — App.jsx, components.jsx 공통 참조용
export const KNOWN_SUBS = [
  "weight","diet","weight_training","cardio",
  "economy",
  "book","wine","coffee",
];

// 아카이브 4섹션 정의 (색상·subs 포함) — ArchiveView, ArchiveEntryCard 공통
export const ARCHIVE_SECTS = [
  { id:"health",  label:"건강", color:"#4A8A5A", bg:"#EBF5EE", text:"#2E6640",
    subs:["weight","diet","weight_training","cardio"] },
  { id:"economy", label:"경제", color:"#2E6FA5", bg:"#E8F2FA", text:"#1A4E7A",
    subs:["economy"] },
  { id:"review",  label:"리뷰", color:"#1A4080", bg:"#E5EAF5", text:"#0F2A60",
    subs:["book","wine","coffee"] },
  { id:"etc",     label:"기타", color:"#7E4FA0", bg:"#F3EBF8", text:"#5A2E80",
    subs:null },
];

// 하단 탭바 아이콘/색상 — BottomTabBar 전용
export const TAB_ITEMS = [
  { id:"all",      label:"홈",      icon:"🏠", color:"#B09520" },
  { id:"briefing", label:"브리핑",  icon:"📋", color:"#6B7C3A" },
  { id:"habit",    label:"습관",    icon:"✨", color:"#2E6FA5" },
  { id:"archive",  label:"아카이브", icon:"🗂",  color:"#7E4FA0" },
];

// ── View constants ──────────────────────────────────
export const VIEWS     = ["주","월","년"];
export const WEEKDAYS  = ["일","월","화","수","목","금","토"];
export const MONTHS_KR = ["1월","2월","3월","4월","5월","6월","7월","8월","9월","10월","11월","12월"];
export const HOURS     = Array.from({length:24},(_,i)=>i);

// ── Helper functions ────────────────────────────────
/** 로컬 타임존 기준 YYYY-MM-DD 문자열 */
export const dateStr = (d) =>
  `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;

/** 카테고리/서브카테고리로 색상 객체 반환 — ARCHIVE_SECTS 기반으로 subs 파생 */
const subsOf = (id) => ARCHIVE_SECTS.find(s => s.id === id)?.subs || [];

export const catOf = (category, sub_category) => {
  if (category === "archive") {
    if (!sub_category) return CATS.find(c=>c.id==="archive") || CATS[0];
    if (subsOf("health").includes(sub_category)) return ARCHIVE_SECTS.find(s=>s.id==="health")  || CATS[2];
    if (subsOf("review").includes(sub_category)) return ARCHIVE_SECTS.find(s=>s.id==="review")  || CATS[2];
    if (sub_category === "economy")              return ARCHIVE_SECTS.find(s=>s.id==="economy") || CATS[2];
    return ARCHIVE_SECTS.find(s=>s.id===sub_category) || CATS.find(c=>c.id==="archive") || CATS[0];
  }
  return CATS.find(c=>c.id===category) || CATS[0];
};

/** 해당 날짜가 속한 주의 7일 배열 (일~토) */
export function getWeekDays(date) {
  const d = new Date(date), day = d.getDay();
  return Array.from({length:7}, (_, i) => {
    const x = new Date(d);
    x.setDate(x.getDate() - day + i);
    return x;
  });
}

/** 월 캘린더 셀 배열 (앞 빈칸 null, 날짜 Date 객체) */
export function getMonthCells(date) {
  const year = date.getFullYear(), month = date.getMonth();
  const first = new Date(year, month, 1);
  const last  = new Date(year, month + 1, 0);
  const cells = [];
  for (let i = 0; i < first.getDay(); i++) cells.push(null);
  for (let d = 1; d <= last.getDate(); d++) cells.push(new Date(year, month, d));
  return cells;
}

// ── Word Bank (중복 제거) ───────────────────────────
export const TOEIC_WORDS = [
  // A
  {word:"abandon", pronunciation:"/əˈbændən/", meaning:"포기하다, 버리다"},
  {word:"accelerate", pronunciation:"/액셀러레이트/", meaning:"가속하다, 촉진하다"},
  {word:"accommodate", pronunciation:"/əˈkɒmədeɪt/", meaning:"수용하다, 편의를 제공하다"},
  {word:"accomplish", pronunciation:"/əˈkʌmplɪʃ/", meaning:"성취하다, 완수하다"},
  {word:"accurate", pronunciation:"/ˈækjərət/", meaning:"정확한, 정밀한"},
  {word:"acclimate", pronunciation:"/ˈækləmeɪt/", meaning:"적응하다"},
  {word:"accumulate", pronunciation:"/əˈkjuːmjəleɪt/", meaning:"축적하다, 모으다"},
  {word:"acquire", pronunciation:"/əˈkwaɪər/", meaning:"획득하다, 습득하다"},
  {word:"adjacent", pronunciation:"/əˈdʒeɪsənt/", meaning:"인접한, 근접한"},
  {word:"adjourn", pronunciation:"/əˈdʒɜːrn/", meaning:"휴회하다, 연기하다"},
  {word:"adjunct", pronunciation:"/ˈædʒʌŋkt/", meaning:"부가물, 보조"},
  {word:"adjustment", pronunciation:"/əˈdʒʌstmənt/", meaning:"조정, 수정"},
  {word:"advent", pronunciation:"/ˈædvent/", meaning:"도래, 출현"},
  {word:"advocacy", pronunciation:"/ˈædvəkəsi/", meaning:"지지, 옹호"},
  {word:"aggregate", pronunciation:"/ˈæɡrɪɡət/", meaning:"합계, 총액"},
  {word:"agenda", pronunciation:"/əˈdʒendə/", meaning:"의제, 안건"},
  {word:"allocation", pronunciation:"/ˌæləˈkeɪʃən/", meaning:"배분, 할당"},
  {word:"allocate", pronunciation:"/ˈæləkeɪt/", meaning:"할당하다, 배분하다"},
  {word:"amend", pronunciation:"/əˈmend/", meaning:"수정하다, 개정하다"},
  {word:"analyze", pronunciation:"/ˈænəlaɪz/", meaning:"분석하다"},
  {word:"annotation", pronunciation:"/ˌænəˈteɪʃən/", meaning:"주석, 메모"},
  {word:"anticipate", pronunciation:"/ænˈtɪsɪpeɪt/", meaning:"예상하다, 기대하다"},
  {word:"apparent", pronunciation:"/əˈpærənt/", meaning:"명백한, 외견상의"},
  {word:"applicable", pronunciation:"/ˈæplɪkəbəl/", meaning:"적용 가능한, 해당되는"},
  {word:"appoint", pronunciation:"/əˈpɔɪnt/", meaning:"임명하다, 지정하다"},
  {word:"appreciate", pronunciation:"/əˈpriːʃieɪt/", meaning:"감사하다, 가치를 인정하다"},
  {word:"appropriate", pronunciation:"/əˈproʊpriət/", meaning:"적절한, 알맞은"},
  {word:"approximately", pronunciation:"/əˈprɒksɪmətli/", meaning:"대략, 약"},
  {word:"arbitration", pronunciation:"/ˌɑːrbɪˈtreɪʃən/", meaning:"중재, 조정"},
  {word:"asset", pronunciation:"/ˈæset/", meaning:"자산, 재산"},
  {word:"assess", pronunciation:"/əˈses/", meaning:"평가하다, 산정하다"},
  {word:"assign", pronunciation:"/əˈsaɪn/", meaning:"할당하다, 배정하다"},
  {word:"assumption", pronunciation:"/əˈsʌmpʃən/", meaning:"가정, 전제"},
  {word:"attain", pronunciation:"/əˈteɪn/", meaning:"달성하다, 이루다"},
  {word:"audit", pronunciation:"/ˈɔːdɪt/", meaning:"감사; 감사하다"},
  {word:"authorize", pronunciation:"/ˈɔːθəraɪz/", meaning:"승인하다, 권한을 부여하다"},
  {word:"available", pronunciation:"/əˈveɪləbəl/", meaning:"이용 가능한, 구할 수 있는"},
  // B
  {word:"benchmark", pronunciation:"/ˈbentʃmɑːrk/", meaning:"기준, 척도; 기준으로 삼다"},
  {word:"beneficial", pronunciation:"/ˌbenɪˈfɪʃəl/", meaning:"유익한, 이로운"},
  {word:"board", pronunciation:"/bɔːrd/", meaning:"이사회; 탑승하다"},
  {word:"bond", pronunciation:"/bɒnd/", meaning:"채권; 유대, 결합"},
  {word:"brainstorm", pronunciation:"/ˈbreɪnstɔːrm/", meaning:"브레인스토밍하다"},
  {word:"breakeven", pronunciation:"/ˈbreɪkˌiːvən/", meaning:"손익 분기점"},
  {word:"brief", pronunciation:"/briːf/", meaning:"간단한; 요약하다"},
  {word:"budget", pronunciation:"/ˈbʌdʒɪt/", meaning:"예산; 예산을 세우다"},
  // C
  {word:"calculate", pronunciation:"/ˈkælkjəleɪt/", meaning:"계산하다, 추정하다"},
  {word:"calibrate", pronunciation:"/ˈkælɪbreɪt/", meaning:"보정하다, 맞추다"},
  {word:"candidate", pronunciation:"/ˈkændɪdeɪt/", meaning:"후보자, 지원자"},
  {word:"capacity", pronunciation:"/kəˈpæsɪti/", meaning:"수용력, 능력, 용량"},
  {word:"cascade", pronunciation:"/kæˈskeɪd/", meaning:"연속 효과; 흘러내리다"},
  {word:"catalyst", pronunciation:"/ˈkætəlɪst/", meaning:"촉매, 촉진제"},
  {word:"category", pronunciation:"/ˈkætəɡɔːri/", meaning:"범주, 분류"},
  {word:"certify", pronunciation:"/ˈsɜːrtɪfaɪ/", meaning:"증명하다, 인증하다"},
  {word:"charter", pronunciation:"/ˈtʃɑːrtər/", meaning:"설립 허가서; 전세하다"},
  {word:"circulate", pronunciation:"/ˈsɜːrkjəleɪt/", meaning:"순환하다, 배포하다"},
  {word:"clarify", pronunciation:"/ˈklærɪfaɪ/", meaning:"명확히 하다, 설명하다"},
  {word:"co-author", pronunciation:"/ˈkoʊˌɔːθər/", meaning:"공동 저자"},
  {word:"coherent", pronunciation:"/koʊˈhɪərənt/", meaning:"일관된, 논리적인"},
  {word:"collaborate", pronunciation:"/kəˈlæbəreɪt/", meaning:"협력하다, 공동 작업하다"},
  {word:"commodity", pronunciation:"/kəˈmɒdɪti/", meaning:"상품, 일용품"},
  {word:"compile", pronunciation:"/kəmˈpaɪl/", meaning:"편집하다, 수집하다"},
  {word:"comply", pronunciation:"/kəmˈplaɪ/", meaning:"따르다, 준수하다"},
  {word:"comprehensive", pronunciation:"/ˌkɒmprɪˈhensɪv/", meaning:"포괄적인, 종합적인"},
  {word:"concentrate", pronunciation:"/ˈkɒnsəntreɪt/", meaning:"집중하다, 농축하다"},
  {word:"concession", pronunciation:"/kənˈseʃən/", meaning:"양보, 특허권"},
  {word:"concur", pronunciation:"/kənˈkɜːr/", meaning:"동의하다, 일치하다"},
  {word:"confiscate", pronunciation:"/ˈkɒnfɪskeɪt/", meaning:"몰수하다, 압수하다"},
  {word:"confirm", pronunciation:"/kənˈfɜːrm/", meaning:"확인하다, 확정하다"},
  {word:"considerable", pronunciation:"/kənˈsɪdərəbəl/", meaning:"상당한, 중요한"},
  {word:"consistently", pronunciation:"/kənˈsɪstəntli/", meaning:"일관되게, 꾸준히"},
  {word:"consolidate", pronunciation:"/kənˈsɒlɪdeɪt/", meaning:"통합하다, 강화하다"},
  {word:"consortium", pronunciation:"/kənˈsɔːrtiəm/", meaning:"컨소시엄, 협회"},
  {word:"contingency", pronunciation:"/kənˈtɪndʒənsi/", meaning:"우발 상황"},
  {word:"contingent", pronunciation:"/kənˈtɪndʒənt/", meaning:"우발적인; 조건부"},
  {word:"contract", pronunciation:"/ˈkɒntrækt/", meaning:"계약(서); 계약을 맺다"},
  {word:"contribute", pronunciation:"/kənˈtrɪbjuːt/", meaning:"기여하다, 공헌하다"},
  {word:"convenient", pronunciation:"/kənˈviːniənt/", meaning:"편리한, 간편한"},
  {word:"convene", pronunciation:"/kənˈviːn/", meaning:"소집하다, 소환하다"},
  {word:"coordinate", pronunciation:"/koʊˈɔːrdɪneɪt/", meaning:"조율하다, 조정하다"},
  {word:"copyright", pronunciation:"/ˈkɒpɪraɪt/", meaning:"저작권"},
  {word:"corporate", pronunciation:"/ˈkɔːrpərɪt/", meaning:"기업의, 법인의"},
  {word:"correspond", pronunciation:"/ˌkɒrɪˈspɒnd/", meaning:"일치하다, 서신 왕래하다"},
  {word:"credential", pronunciation:"/krɪˈdenʃəl/", meaning:"자격증, 신임장"},
  {word:"currently", pronunciation:"/ˈkɜːrəntli/", meaning:"현재, 지금"},
  // D
  {word:"deadline", pronunciation:"/ˈdedlaɪn/", meaning:"마감일, 기한"},
  {word:"decrease", pronunciation:"/dɪˈkriːs/", meaning:"감소하다, 줄다; 감소"},
  {word:"deficit", pronunciation:"/ˈdefɪsɪt/", meaning:"결손, 부족"},
  {word:"delegate", pronunciation:"/ˈdelɪɡeɪt/", meaning:"위임하다; 대표, 대리인"},
  {word:"demonstrate", pronunciation:"/ˈdemənstreɪt/", meaning:"증명하다, 시연하다"},
  {word:"depreciation", pronunciation:"/dɪˌpriːʃiˈeɪʃən/", meaning:"감가상각, 가치 하락"},
  {word:"derivative", pronunciation:"/dɪˈrɪvətɪv/", meaning:"파생 상품; 파생된"},
  {word:"determine", pronunciation:"/dɪˈtɜːrmɪn/", meaning:"결정하다, 판단하다"},
  {word:"deter", pronunciation:"/dɪˈtɜːr/", meaning:"단념시키다, 억제하다"},
  {word:"develop", pronunciation:"/dɪˈveləp/", meaning:"개발하다, 발전시키다"},
  {word:"discretion", pronunciation:"/dɪˈskreʃən/", meaning:"재량권, 분별력"},
  {word:"dispatch", pronunciation:"/dɪˈspætʃ/", meaning:"발송하다; 급파"},
  {word:"disposition", pronunciation:"/ˌdɪspəˈzɪʃən/", meaning:"처분, 성향"},
  {word:"diverse", pronunciation:"/daɪˈvɜːrs/", meaning:"다양한, 여러 종류의"},
  {word:"document", pronunciation:"/ˈdɒkjəmənt/", meaning:"문서; 기록하다"},
  {word:"downsize", pronunciation:"/ˈdaʊnsaɪz/", meaning:"규모를 축소하다"},
  {word:"draft", pronunciation:"/drɑːft/", meaning:"초안; 초안을 작성하다"},
  // E
  {word:"efficient", pronunciation:"/ɪˈfɪʃənt/", meaning:"효율적인, 능률적인"},
  {word:"eligible", pronunciation:"/ˈelɪdʒɪbəl/", meaning:"자격이 있는, 적합한"},
  {word:"emphasize", pronunciation:"/ˈemfəsaɪz/", meaning:"강조하다, 역설하다"},
  {word:"enable", pronunciation:"/ɪˈneɪbəl/", meaning:"가능하게 하다, 허용하다"},
  {word:"endorse", pronunciation:"/ɪnˈdɔːrs/", meaning:"서명하다, 보증하다"},
  {word:"enhance", pronunciation:"/ɪnˈhæns/", meaning:"향상시키다, 높이다"},
  {word:"ensure", pronunciation:"/ɪnˈʃʊər/", meaning:"보장하다, 확실히 하다"},
  {word:"equity", pronunciation:"/ˈekwɪti/", meaning:"지분, 자기 자본; 공정"},
  {word:"escalate", pronunciation:"/ˈeskəleɪt/", meaning:"단계적으로 높아지다"},
  {word:"establish", pronunciation:"/ɪˈstæblɪʃ/", meaning:"설립하다, 확립하다"},
  {word:"evaluate", pronunciation:"/ɪˈvæljueɪt/", meaning:"평가하다, 검토하다"},
  {word:"exceed", pronunciation:"/ɪkˈsiːd/", meaning:"초과하다, 능가하다"},
  {word:"execute", pronunciation:"/ˈeksɪkjuːt/", meaning:"실행하다, 처형하다"},
  {word:"exemplary", pronunciation:"/ɪɡˈzempləri/", meaning:"모범적인"},
  {word:"exhaustive", pronunciation:"/ɪɡˈzɔːstɪv/", meaning:"철저한, 완전한"},
  {word:"expedite", pronunciation:"/ˈekspɪdaɪt/", meaning:"촉진하다, 신속히 처리하다"},
  {word:"expand", pronunciation:"/ɪkˈspænd/", meaning:"확장하다, 늘리다"},
  {word:"expertise", pronunciation:"/ˌekspɜːrˈtiːz/", meaning:"전문 지식, 전문성"},
  {word:"expose", pronunciation:"/ɪkˈspoʊz/", meaning:"노출시키다, 드러내다"},
  // F
  {word:"facilitate", pronunciation:"/fəˈsɪlɪteɪt/", meaning:"용이하게 하다, 촉진하다"},
  {word:"feasibility", pronunciation:"/ˌfiːzəˈbɪlɪti/", meaning:"타당성, 실현 가능성"},
  {word:"feasible", pronunciation:"/ˈfiːzɪbəl/", meaning:"실현 가능한, 타당한"},
  {word:"finalize", pronunciation:"/ˈfaɪnəlaɪz/", meaning:"마무리하다, 확정하다"},
  {word:"fluctuation", pronunciation:"/ˌflʌktʃuˈeɪʃən/", meaning:"변동, 파동"},
  {word:"forthcoming", pronunciation:"/ˌfɔːrθˈkʌmɪŋ/", meaning:"곧 있을, 다가오는"},
  {word:"franchise", pronunciation:"/ˈfræntʃaɪz/", meaning:"프랜차이즈; 선거권"},
  // G
  {word:"gauge", pronunciation:"/ɡeɪdʒ/", meaning:"측정하다; 계기"},
  {word:"ground", pronunciation:"/ɡraʊnd/", meaning:"근거; 기반으로 하다"},
  // I
  {word:"initiative", pronunciation:"/ɪˈnɪʃətɪv/", meaning:"주도권, 계획"},
  {word:"intangible", pronunciation:"/ɪnˈtændʒɪbəl/", meaning:"무형의, 눈에 보이지 않는"},
  {word:"integral", pronunciation:"/ˈɪntɪɡrəl/", meaning:"필수적인, 완전한"},
  {word:"interim", pronunciation:"/ˈɪntərɪm/", meaning:"중간의, 임시의"},
  {word:"intrinsic", pronunciation:"/ɪnˈtrɪnsɪk/", meaning:"본질적인, 고유한"},
  // L
  {word:"lapse", pronunciation:"/læps/", meaning:"경과, 실수; 실효되다"},
  {word:"lucrative", pronunciation:"/ˈluːkrətɪv/", meaning:"수익성이 좋은"},
  // M
  {word:"meticulous", pronunciation:"/mɪˈtɪkjələs/", meaning:"꼼꼼한, 세심한"},
  // N
  {word:"nominal", pronunciation:"/ˈnɒmɪnəl/", meaning:"명목상의, 미미한"},
  // O
  {word:"obsolete", pronunciation:"/ˈɒbsəliːt/", meaning:"구식의, 더 이상 쓸모없는"},
  // P
  {word:"paramount", pronunciation:"/ˈpærəmaʊnt/", meaning:"가장 중요한, 최고의"},
  {word:"parity", pronunciation:"/ˈpærɪti/", meaning:"동등, 균형"},
  {word:"perpetual", pronunciation:"/pərˈpetʃuəl/", meaning:"영구적인, 지속적인"},
  {word:"preliminary", pronunciation:"/prɪˈlɪmɪnəri/", meaning:"예비의, 준비의"},
  {word:"premise", pronunciation:"/ˈpremɪs/", meaning:"전제; 구내"},
  {word:"proactive", pronunciation:"/ˌproʊˈæktɪv/", meaning:"능동적인, 사전 예방적인"},
  {word:"proficiency", pronunciation:"/prəˈfɪʃənsi/", meaning:"능숙함, 유창함"},
  {word:"prohibit", pronunciation:"/prəˈhɪbɪt/", meaning:"금지하다"},
  {word:"projection", pronunciation:"/prəˈdʒekʃən/", meaning:"예측, 전망, 투영"},
  {word:"proofread", pronunciation:"/ˈpruːfriːd/", meaning:"교정하다"},
  {word:"proprietary", pronunciation:"/prəˈpraɪətəri/", meaning:"소유권의, 독점적인"},
  {word:"prototype", pronunciation:"/ˈproʊtətaɪp/", meaning:"원형, 시제품"},
  {word:"provision", pronunciation:"/prəˈvɪʒən/", meaning:"조항, 규정; 공급"},
  {word:"proximity", pronunciation:"/prɒkˈsɪmɪti/", meaning:"근접성, 인접"},
  {word:"pursue", pronunciation:"/pərˈsjuː/", meaning:"추구하다, 쫓다"},
  // Q
  {word:"quantify", pronunciation:"/ˈkwɒntɪfaɪ/", meaning:"정량화하다"},
  {word:"query", pronunciation:"/ˈkwɪəri/", meaning:"질문; 질의하다"},
  {word:"quota", pronunciation:"/ˈkwoʊtə/", meaning:"할당량, 쿼터"},
  // R
  {word:"ratify", pronunciation:"/ˈrætɪfaɪ/", meaning:"비준하다, 승인하다"},
  {word:"reallocation", pronunciation:"/ˌriːæləˈkeɪʃən/", meaning:"재배분, 재할당"},
  {word:"receipt", pronunciation:"/rɪˈsiːt/", meaning:"영수증, 수령"},
  {word:"reconcile", pronunciation:"/ˈrekənsaɪl/", meaning:"조화시키다, 화해시키다"},
  {word:"redundancy", pronunciation:"/rɪˈdʌndənsi/", meaning:"중복, 잉여, 정리해고"},
  {word:"refund", pronunciation:"/ˈriːfʌnd/", meaning:"환불; 환불하다"},
  {word:"reimburse", pronunciation:"/ˌriːɪmˈbɜːrs/", meaning:"상환하다, 변제하다"},
  {word:"reinforce", pronunciation:"/ˌriːɪnˈfɔːrs/", meaning:"강화하다, 보강하다"},
  {word:"relocate", pronunciation:"/ˌriːloʊˈkeɪt/", meaning:"이전하다, 이동하다"},
  {word:"remittance", pronunciation:"/rɪˈmɪtəns/", meaning:"송금, 입금"},
  {word:"remunerate", pronunciation:"/rɪˈmjuːnəreɪt/", meaning:"보수를 주다"},
  {word:"replenish", pronunciation:"/rɪˈplenɪʃ/", meaning:"보충하다, 다시 채우다"},
  {word:"replicate", pronunciation:"/ˈreplɪkeɪt/", meaning:"복제하다, 반복하다"},
  {word:"report", pronunciation:"/rɪˈpɔːrt/", meaning:"보고하다; 보고서"},
  {word:"represent", pronunciation:"/ˌreprɪˈzent/", meaning:"대표하다, 나타내다"},
  {word:"reschedule", pronunciation:"/riːˈʃedjuːl/", meaning:"일정을 변경하다"},
  {word:"resilient", pronunciation:"/rɪˈzɪliənt/", meaning:"회복력 있는, 탄력적인"},
  {word:"restrict", pronunciation:"/rɪˈstrɪkt/", meaning:"제한하다, 규제하다"},
  {word:"restructure", pronunciation:"/riːˈstrʌktʃər/", meaning:"구조 조정하다"},
  {word:"retain", pronunciation:"/rɪˈteɪn/", meaning:"유지하다, 보유하다"},
  {word:"retrospective", pronunciation:"/ˌretrəˈspektɪv/", meaning:"소급적인; 회고"},
  {word:"rigorous", pronunciation:"/ˈrɪɡərəs/", meaning:"엄격한, 철저한"},
  {word:"robust", pronunciation:"/roʊˈbʌst/", meaning:"강건한, 견고한"},
  // S
  {word:"sanction", pronunciation:"/ˈsæŋkʃən/", meaning:"제재; 승인하다"},
  {word:"scalable", pronunciation:"/ˈskeɪləbəl/", meaning:"확장 가능한"},
  {word:"scrutinize", pronunciation:"/ˈskruːtɪnaɪz/", meaning:"면밀히 검토하다"},
  {word:"scrutiny", pronunciation:"/ˈskruːtɪni/", meaning:"면밀한 검토, 조사"},
  {word:"seamless", pronunciation:"/ˈsiːmləs/", meaning:"원활한, 매끄러운"},
  {word:"sector", pronunciation:"/ˈsektər/", meaning:"분야, 부문"},
  {word:"segment", pronunciation:"/ˈseɡmənt/", meaning:"구분하다; 구분, 세그먼트"},
  {word:"sequential", pronunciation:"/sɪˈkwenʃəl/", meaning:"순차적인"},
  {word:"settlement", pronunciation:"/ˈsetəlmənt/", meaning:"해결, 정산, 결제"},
  {word:"shareholder", pronunciation:"/ˈʃeəhoʊldər/", meaning:"주주"},
  {word:"shortage", pronunciation:"/ˈʃɔːrtɪdʒ/", meaning:"부족, 결핍"},
  {word:"simulate", pronunciation:"/ˈsɪmjəleɪt/", meaning:"모의 실험하다, 모방하다"},
  {word:"solicitation", pronunciation:"/səˌlɪsɪˈteɪʃən/", meaning:"권유, 청원"},
  {word:"specification", pronunciation:"/ˌspesɪfɪˈkeɪʃən/", meaning:"명세서, 사양"},
  {word:"stakeholder", pronunciation:"/ˈsteɪkhoʊldər/", meaning:"이해관계자"},
  {word:"standardize", pronunciation:"/ˈstændədaɪz/", meaning:"표준화하다"},
  {word:"statute", pronunciation:"/ˈstætʃuːt/", meaning:"법령, 규정"},
  {word:"streamline", pronunciation:"/ˈstriːmlaɪn/", meaning:"간소화하다, 효율화하다"},
  {word:"stringent", pronunciation:"/ˈstrɪndʒənt/", meaning:"엄격한, 까다로운"},
  {word:"subordinate", pronunciation:"/səˈbɔːrdɪnɪt/", meaning:"부하, 하위의"},
  {word:"subsidize", pronunciation:"/ˈsʌbsɪdaɪz/", meaning:"보조금을 주다"},
  {word:"substantial", pronunciation:"/səbˈstænʃəl/", meaning:"상당한, 실질적인"},
  {word:"succession", pronunciation:"/səkˈseʃən/", meaning:"연속, 승계"},
  {word:"successively", pronunciation:"/səkˈsesɪvli/", meaning:"연속해서, 잇달아"},
  {word:"surplus", pronunciation:"/ˈsɜːrpləs/", meaning:"잉여, 흑자"},
  {word:"suspend", pronunciation:"/səˈspend/", meaning:"중단하다, 정지시키다"},
  {word:"synergy", pronunciation:"/ˈsɪnədʒi/", meaning:"시너지, 상승효과"},
  {word:"systematic", pronunciation:"/ˌsɪstəˈmætɪk/", meaning:"체계적인, 조직적인"},
  // T
  {word:"tactical", pronunciation:"/ˈtæktɪkəl/", meaning:"전술적인"},
  {word:"tangible", pronunciation:"/ˈtændʒɪbəl/", meaning:"유형의, 실제적인"},
  {word:"tariff", pronunciation:"/ˈtærɪf/", meaning:"관세, 요금표"},
  {word:"taskforce", pronunciation:"/ˈtɑːskfɔːrs/", meaning:"특별팀, 태스크포스"},
  {word:"technical", pronunciation:"/ˈteknɪkəl/", meaning:"기술적인, 전문적인"},
  {word:"tenure", pronunciation:"/ˈtenjər/", meaning:"재직 기간, 임기"},
  {word:"threshold", pronunciation:"/ˈθreʃhoʊld/", meaning:"임계값, 한계점"},
  {word:"timeline", pronunciation:"/ˈtaɪmlaɪn/", meaning:"일정표, 연대표"},
  {word:"transaction", pronunciation:"/trænˈzækʃən/", meaning:"거래, 처리"},
  {word:"transition", pronunciation:"/trænˈzɪʃən/", meaning:"전환, 이행"},
  {word:"transparent", pronunciation:"/trænsˈpærənt/", meaning:"투명한, 솔직한"},
  {word:"turnaround", pronunciation:"/ˈtɜːrəraʊnd/", meaning:"방향 전환, 회복"},
  {word:"turnover", pronunciation:"/ˈtɜːrnoʊvər/", meaning:"이직률, 매출액"},
  // U
  {word:"unanimous", pronunciation:"/juːˈnænɪməs/", meaning:"만장일치의"},
  {word:"undermine", pronunciation:"/ˌʌndərˈmaɪn/", meaning:"약화시키다, 훼손하다"},
  {word:"uniform", pronunciation:"/ˈjuːnɪfɔːrm/", meaning:"균일한, 통일된; 제복"},
  {word:"unilateral", pronunciation:"/ˌjuːnɪˈlætərəl/", meaning:"일방적인"},
  {word:"unprecedented", pronunciation:"/ʌnˈpresɪdentɪd/", meaning:"전례 없는"},
  {word:"update", pronunciation:"/ˈʌpdeɪt/", meaning:"업데이트하다; 최신 정보"},
  {word:"upgrade", pronunciation:"/ˈʌpɡreɪd/", meaning:"업그레이드하다, 향상시키다"},
  {word:"urgency", pronunciation:"/ˈɜːrdʒənsi/", meaning:"긴급함, 시급성"},
  // V
  {word:"vacancy", pronunciation:"/ˈveɪkənsi/", meaning:"공석, 빈자리"},
  {word:"variance", pronunciation:"/ˈveəriəns/", meaning:"차이, 변동"},
  {word:"vendor", pronunciation:"/ˈvendər/", meaning:"판매자, 공급업체"},
  {word:"venture", pronunciation:"/ˈventʃər/", meaning:"모험; 벤처 사업"},
  {word:"versatile", pronunciation:"/ˈvɜːrsətaɪl/", meaning:"다재다능한, 다용도의"},
  {word:"vested", pronunciation:"/ˈvestɪd/", meaning:"기득권이 있는, 확정된"},
  {word:"viable", pronunciation:"/ˈvaɪəbəl/", meaning:"실행 가능한"},
  {word:"visibility", pronunciation:"/ˌvɪzɪˈbɪlɪti/", meaning:"가시성, 인지도"},
  {word:"vital", pronunciation:"/ˈvaɪtəl/", meaning:"필수적인, 생명의"},
  {word:"volume", pronunciation:"/ˈvɒljuːm/", meaning:"양, 용량, 권"},
  {word:"vulnerability", pronunciation:"/ˌvʌlnərəˈbɪlɪti/", meaning:"취약성, 약점"},
  // W
  {word:"waive", pronunciation:"/weɪv/", meaning:"포기하다, 면제하다"},
  {word:"warranty", pronunciation:"/ˈwɒrənti/", meaning:"보증, 품질 보증"},
  {word:"wholesale", pronunciation:"/ˈhoʊlseɪl/", meaning:"도매; 대규모의"},
  {word:"workforce", pronunciation:"/ˈwɜːrkfɔːrs/", meaning:"노동력, 인력"},
  {word:"workload", pronunciation:"/ˈwɜːrkloʊd/", meaning:"업무량, 작업 부하"},
  // A (추가)
  {word:"abide", pronunciation:"/əˈbaɪd/", meaning:"따르다, 준수하다"},
  {word:"abolish", pronunciation:"/əˈbɒlɪʃ/", meaning:"폐지하다, 없애다"},
  {word:"absence", pronunciation:"/ˈæbsəns/", meaning:"부재, 결석"},
  {word:"abstract", pronunciation:"/ˈæbstrækt/", meaning:"요약; 추상적인"},
  {word:"acceptance", pronunciation:"/əkˈseptəns/", meaning:"수락, 승인"},
  {word:"access", pronunciation:"/ˈækses/", meaning:"접근; 접근하다"},
  {word:"acclaim", pronunciation:"/əˈkleɪm/", meaning:"칭찬하다; 갈채"},
  {word:"account", pronunciation:"/əˈkaʊnt/", meaning:"계좌; 설명하다"},
  {word:"acknowledge", pronunciation:"/əkˈnɒlɪdʒ/", meaning:"인정하다, 감사하다"},
  {word:"activate", pronunciation:"/ˈæktɪveɪt/", meaning:"활성화하다"},
  {word:"adapt", pronunciation:"/əˈdæpt/", meaning:"적응하다, 조정하다"},
  {word:"address", pronunciation:"/əˈdres/", meaning:"주소; 처리하다"},
  {word:"adequate", pronunciation:"/ˈædɪkwət/", meaning:"적절한, 충분한"},
  {word:"adhere", pronunciation:"/ədˈhɪər/", meaning:"고수하다, 준수하다"},
  {word:"adopt", pronunciation:"/əˈdɒpt/", meaning:"채택하다, 도입하다"},
  {word:"advance", pronunciation:"/ədˈvæns/", meaning:"발전; 전진하다"},
  {word:"affect", pronunciation:"/əˈfekt/", meaning:"영향을 미치다"},
  {word:"afford", pronunciation:"/əˈfɔːrd/", meaning:"여유가 있다, 제공하다"},
  {word:"agency", pronunciation:"/ˈeɪdʒənsi/", meaning:"대리점, 기관"},
  {word:"alert", pronunciation:"/əˈlɜːrt/", meaning:"경고; 알리다"},
  {word:"align", pronunciation:"/əˈlaɪn/", meaning:"정렬하다, 맞추다"},
  {word:"allot", pronunciation:"/əˈlɒt/", meaning:"할당하다, 배정하다"},
  {word:"alter", pronunciation:"/ˈɔːltər/", meaning:"변경하다, 바꾸다"},
  {word:"alternative", pronunciation:"/ɔːlˈtɜːrnətɪv/", meaning:"대안; 대안적인"},
  {word:"annual", pronunciation:"/ˈænjuəl/", meaning:"연간의, 매년의"},
  {word:"appeal", pronunciation:"/əˈpiːl/", meaning:"호소; 매력"},
  {word:"application", pronunciation:"/ˌæplɪˈkeɪʃən/", meaning:"지원서; 적용"},
  {word:"approve", pronunciation:"/əˈpruːv/", meaning:"승인하다"},
  {word:"archive", pronunciation:"/ˈɑːrkaɪv/", meaning:"기록 보관소; 보관하다"},
  {word:"aspect", pronunciation:"/ˈæspekt/", meaning:"측면, 양상"},
  {word:"assemble", pronunciation:"/əˈsembəl/", meaning:"조립하다, 모으다"},
  {word:"attest", pronunciation:"/əˈtest/", meaning:"증명하다, 입증하다"},
  {word:"attribute", pronunciation:"/ˈætrɪbjuːt/", meaning:"특성; 귀속시키다"},
  {word:"auction", pronunciation:"/ˈɔːkʃən/", meaning:"경매; 경매하다"},
  // B (추가)
  {word:"balance", pronunciation:"/ˈbæləns/", meaning:"균형; 잔액"},
  {word:"ballot", pronunciation:"/ˈbælət/", meaning:"투표; 투표하다"},
  {word:"bankrupt", pronunciation:"/ˈbæŋkrʌpt/", meaning:"파산한; 파산하다"},
  {word:"barrier", pronunciation:"/ˈbæriər/", meaning:"장벽, 장애물"},
  {word:"behalf", pronunciation:"/bɪˈhæf/", meaning:"이익, 대신"},
  {word:"bilateral", pronunciation:"/baɪˈlætərəl/", meaning:"쌍방의, 양측의"},
  {word:"billing", pronunciation:"/ˈbɪlɪŋ/", meaning:"청구서 발송"},
  {word:"boost", pronunciation:"/buːst/", meaning:"높이다, 촉진하다"},
  {word:"branch", pronunciation:"/bræntʃ/", meaning:"지점, 분점"},
  {word:"breakthrough", pronunciation:"/ˈbreɪkθruː/", meaning:"돌파구, 획기적 발전"},
  // C (추가)
  {word:"cancel", pronunciation:"/ˈkænsəl/", meaning:"취소하다"},
  {word:"capital", pronunciation:"/ˈkæpɪtəl/", meaning:"자본; 수도"},
  {word:"capture", pronunciation:"/ˈkæptʃər/", meaning:"포착하다, 획득하다"},
  {word:"carrier", pronunciation:"/ˈkæriər/", meaning:"운송업체; 이동통신사"},
  {word:"chronic", pronunciation:"/ˈkrɒnɪk/", meaning:"만성적인"},
  {word:"cite", pronunciation:"/saɪt/", meaning:"인용하다, 언급하다"},
  {word:"claim", pronunciation:"/kleɪm/", meaning:"주장하다; 청구"},
  {word:"clientele", pronunciation:"/ˌkliːənˈtel/", meaning:"고객층"},
  {word:"closure", pronunciation:"/ˈkloʊʒər/", meaning:"폐쇄, 종결"},
  {word:"coalition", pronunciation:"/ˌkoʊəˈlɪʃən/", meaning:"연합, 연립"},
  {word:"code", pronunciation:"/koʊd/", meaning:"규정; 코드"},
  {word:"coincide", pronunciation:"/ˌkoʊɪnˈsaɪd/", meaning:"일치하다, 동시에 일어나다"},
  {word:"collateral", pronunciation:"/kəˈlætərəl/", meaning:"담보; 부수적인"},
  {word:"commission", pronunciation:"/kəˈmɪʃən/", meaning:"수수료; 위임하다"},
  {word:"commitment", pronunciation:"/kəˈmɪtmənt/", meaning:"헌신, 약속"},
  {word:"compensation", pronunciation:"/ˌkɒmpənˈseɪʃən/", meaning:"보상, 급여"},
  {word:"competent", pronunciation:"/ˈkɒmpɪtənt/", meaning:"유능한, 능숙한"},
  {word:"competitive", pronunciation:"/kəmˈpetɪtɪv/", meaning:"경쟁력 있는"},
  {word:"complaint", pronunciation:"/kəmˈpleɪnt/", meaning:"불만, 항의"},
  {word:"complexity", pronunciation:"/kəmˈpleksɪti/", meaning:"복잡성"},
  {word:"compliance", pronunciation:"/kəmˈplaɪəns/", meaning:"준수, 순응"},
  {word:"component", pronunciation:"/kəmˈpoʊnənt/", meaning:"구성 요소, 부품"},
  {word:"concise", pronunciation:"/kənˈsaɪs/", meaning:"간결한, 명료한"},
  {word:"conduct", pronunciation:"/ˈkɒndʌkt/", meaning:"수행하다; 행동"},
  {word:"confidential", pronunciation:"/ˌkɒnfɪˈdenʃəl/", meaning:"기밀의, 비밀의"},
  {word:"conflict", pronunciation:"/ˈkɒnflɪkt/", meaning:"충돌, 갈등"},
  {word:"consent", pronunciation:"/kənˈsent/", meaning:"동의; 동의하다"},
  {word:"consistent", pronunciation:"/kənˈsɪstənt/", meaning:"일관된, 꾸준한"},
  {word:"constructive", pronunciation:"/kənˈstrʌktɪv/", meaning:"건설적인"},
  {word:"consult", pronunciation:"/kənˈsʌlt/", meaning:"상담하다, 자문하다"},
  {word:"consumer", pronunciation:"/kənˈsjuːmər/", meaning:"소비자"},
  {word:"contact", pronunciation:"/ˈkɒntækt/", meaning:"연락하다; 연락처"},
  {word:"convention", pronunciation:"/kənˈvenʃən/", meaning:"관례; 대회"},
  {word:"conversion", pronunciation:"/kənˈvɜːrʒən/", meaning:"전환, 변환"},
  {word:"conviction", pronunciation:"/kənˈvɪkʃən/", meaning:"확신; 유죄 판결"},
  {word:"cope", pronunciation:"/koʊp/", meaning:"대처하다, 극복하다"},
  {word:"core", pronunciation:"/kɔːr/", meaning:"핵심; 중심의"},
  {word:"cost", pronunciation:"/kɒst/", meaning:"비용; 비용이 들다"},
  {word:"council", pronunciation:"/ˈkaʊnsəl/", meaning:"위원회, 의회"},
  {word:"counterpart", pronunciation:"/ˈkaʊntərpɑːrt/", meaning:"상대방, 대응물"},
  {word:"coverage", pronunciation:"/ˈkʌvərɪdʒ/", meaning:"보도; 보험 범위"},
  {word:"criteria", pronunciation:"/kraɪˈtɪəriə/", meaning:"기준, 판단 기준"},
  {word:"crucial", pronunciation:"/ˈkruːʃəl/", meaning:"결정적인, 중요한"},
  {word:"currency", pronunciation:"/ˈkɜːrənsi/", meaning:"통화, 화폐"},
  {word:"custom", pronunciation:"/ˈkʌstəm/", meaning:"관습; 맞춤의"},
  {word:"cutback", pronunciation:"/ˈkʌtbæk/", meaning:"삭감, 축소"},
  // D (추가)
  {word:"damage", pronunciation:"/ˈdæmɪdʒ/", meaning:"손해; 손상시키다"},
  {word:"deal", pronunciation:"/diːl/", meaning:"거래; 처리하다"},
  {word:"dealer", pronunciation:"/ˈdiːlər/", meaning:"판매상, 딜러"},
  {word:"debt", pronunciation:"/det/", meaning:"부채, 빚"},
  {word:"decision", pronunciation:"/dɪˈsɪʒən/", meaning:"결정, 판단"},
  {word:"decline", pronunciation:"/dɪˈklaɪn/", meaning:"감소하다; 거절하다"},
  {word:"deduct", pronunciation:"/dɪˈdʌkt/", meaning:"공제하다, 빼다"},
  {word:"deficiency", pronunciation:"/dɪˈfɪʃənsi/", meaning:"결핍, 부족"},
  {word:"delay", pronunciation:"/dɪˈleɪ/", meaning:"지연; 미루다"},
  {word:"demand", pronunciation:"/dɪˈmænd/", meaning:"수요; 요구하다"},
  {word:"departure", pronunciation:"/dɪˈpɑːrtʃər/", meaning:"출발; 이탈"},
  {word:"deposit", pronunciation:"/dɪˈpɒzɪt/", meaning:"예금; 보증금"},
  {word:"describe", pronunciation:"/dɪˈskraɪb/", meaning:"묘사하다, 설명하다"},
  {word:"designate", pronunciation:"/ˈdezɪɡneɪt/", meaning:"지정하다, 임명하다"},
  {word:"detail", pronunciation:"/ˈdiːteɪl/", meaning:"세부 사항; 자세히 설명하다"},
  {word:"deteriorate", pronunciation:"/dɪˈtɪəriəreɪt/", meaning:"악화되다"},
  {word:"device", pronunciation:"/dɪˈvaɪs/", meaning:"장치, 기기"},
  {word:"diminish", pronunciation:"/dɪˈmɪnɪʃ/", meaning:"감소하다, 줄이다"},
  {word:"disclose", pronunciation:"/dɪsˈkloʊz/", meaning:"공개하다, 밝히다"},
  {word:"discount", pronunciation:"/ˈdɪskaʊnt/", meaning:"할인; 할인하다"},
  {word:"distribute", pronunciation:"/dɪˈstrɪbjuːt/", meaning:"배포하다, 분배하다"},
  {word:"district", pronunciation:"/ˈdɪstrɪkt/", meaning:"지구, 지역"},
  {word:"dividend", pronunciation:"/ˈdɪvɪdend/", meaning:"배당금"},
  {word:"dominate", pronunciation:"/ˈdɒmɪneɪt/", meaning:"지배하다, 우세하다"},
  {word:"donate", pronunciation:"/doʊˈneɪt/", meaning:"기부하다, 기증하다"},
  {word:"due", pronunciation:"/djuː/", meaning:"기한이 된; 예정된"},
  {word:"durable", pronunciation:"/ˈdjʊərəbəl/", meaning:"내구성 있는, 오래가는"},
  // E (추가)
  {word:"earnings", pronunciation:"/ˈɜːrnɪŋz/", meaning:"수입, 소득"},
  {word:"effect", pronunciation:"/ɪˈfekt/", meaning:"효과; 초래하다"},
  {word:"enforce", pronunciation:"/ɪnˈfɔːrs/", meaning:"시행하다, 집행하다"},
  {word:"engage", pronunciation:"/ɪnˈɡeɪdʒ/", meaning:"참여하다, 고용하다"},
  {word:"equip", pronunciation:"/ɪˈkwɪp/", meaning:"장착하다, 갖추다"},
  {word:"estimate", pronunciation:"/ˈestɪmɪt/", meaning:"추정하다; 견적"},
  {word:"evident", pronunciation:"/ˈevɪdənt/", meaning:"명백한, 분명한"},
  {word:"exception", pronunciation:"/ɪkˈsepʃən/", meaning:"예외, 제외"},
  {word:"exclusive", pronunciation:"/ɪkˈskluːsɪv/", meaning:"독점적인, 배타적인"},
  {word:"exempt", pronunciation:"/ɪɡˈzemt/", meaning:"면제하다; 면제된"},
  {word:"exert", pronunciation:"/ɪɡˈzɜːrt/", meaning:"발휘하다, 행사하다"},
  {word:"exhibit", pronunciation:"/ɪɡˈzɪbɪt/", meaning:"전시하다; 전시물"},
  {word:"expense", pronunciation:"/ɪkˈspens/", meaning:"비용, 경비"},
  {word:"explicit", pronunciation:"/ɪkˈsplɪsɪt/", meaning:"명시적인, 분명한"},
  {word:"exposure", pronunciation:"/ɪkˈspoʊʒər/", meaning:"노출; 폭로"},
  {word:"extension", pronunciation:"/ɪkˈstenʃən/", meaning:"연장; 내선번호"},
  {word:"extensive", pronunciation:"/ɪkˈstensɪv/", meaning:"광범위한, 대규모의"},
  // F (추가)
  {word:"factor", pronunciation:"/ˈfæktər/", meaning:"요인, 요소"},
  {word:"failure", pronunciation:"/ˈfeɪljər/", meaning:"실패, 고장"},
  {word:"favorable", pronunciation:"/ˈfeɪvərəbəl/", meaning:"유리한, 호의적인"},
  {word:"figure", pronunciation:"/ˈfɪɡjər/", meaning:"수치; 인물"},
  {word:"fiscal", pronunciation:"/ˈfɪskəl/", meaning:"재정의, 회계의"},
  {word:"flexible", pronunciation:"/ˈfleksɪbəl/", meaning:"유연한, 융통성 있는"},
  {word:"forecast", pronunciation:"/ˈfɔːrkæst/", meaning:"예측; 예측하다"},
  {word:"formal", pronunciation:"/ˈfɔːrməl/", meaning:"공식적인, 격식 있는"},
  {word:"formula", pronunciation:"/ˈfɔːrmjələ/", meaning:"공식, 방식"},
  {word:"foundation", pronunciation:"/faʊnˈdeɪʃən/", meaning:"기반, 재단"},
  {word:"freight", pronunciation:"/freɪt/", meaning:"화물; 운송하다"},
  {word:"fulfill", pronunciation:"/fʊlˈfɪl/", meaning:"이행하다, 충족하다"},
  {word:"function", pronunciation:"/ˈfʌŋkʃən/", meaning:"기능; 작동하다"},
  {word:"fund", pronunciation:"/fʌnd/", meaning:"자금; 자금을 대다"},
  // G (추가)
  {word:"generate", pronunciation:"/ˈdʒenəreɪt/", meaning:"생성하다, 창출하다"},
  {word:"grant", pronunciation:"/ɡrænt/", meaning:"보조금; 허가하다"},
  {word:"guideline", pronunciation:"/ˈɡaɪdlaɪn/", meaning:"지침, 가이드라인"},
  // H (추가)
  {word:"handle", pronunciation:"/ˈhændəl/", meaning:"처리하다; 손잡이"},
  {word:"headquarters", pronunciation:"/ˈhedˌkwɔːrtərz/", meaning:"본사, 본부"},
  {word:"highlight", pronunciation:"/ˈhaɪlaɪt/", meaning:"강조하다; 주요 내용"},
  {word:"hire", pronunciation:"/haɪər/", meaning:"고용하다; 임대하다"},
  // I (추가)
  {word:"implement", pronunciation:"/ˈɪmplɪment/", meaning:"시행하다, 실행하다"},
  {word:"impose", pronunciation:"/ɪmˈpoʊz/", meaning:"부과하다, 강요하다"},
  {word:"incentive", pronunciation:"/ɪnˈsentɪv/", meaning:"장려금, 동기"},
  {word:"indicate", pronunciation:"/ˈɪndɪkeɪt/", meaning:"나타내다, 가리키다"},
  {word:"individual", pronunciation:"/ˌɪndɪˈvɪdʒuəl/", meaning:"개인; 개별적인"},
  {word:"inform", pronunciation:"/ɪnˈfɔːrm/", meaning:"알리다, 통보하다"},
  {word:"infrastructure", pronunciation:"/ˈɪnfrəˌstrʌktʃər/", meaning:"기반 시설"},
  {word:"inspect", pronunciation:"/ɪnˈspekt/", meaning:"검사하다, 점검하다"},
  {word:"insurance", pronunciation:"/ɪnˈʃʊərəns/", meaning:"보험"},
  {word:"interest", pronunciation:"/ˈɪntrəst/", meaning:"이자; 관심"},
  {word:"interpret", pronunciation:"/ɪnˈtɜːrprɪt/", meaning:"해석하다, 통역하다"},
  {word:"inventory", pronunciation:"/ˈɪnvəntɔːri/", meaning:"재고; 재고 목록"},
  {word:"invest", pronunciation:"/ɪnˈvest/", meaning:"투자하다"},
  {word:"invoice", pronunciation:"/ˈɪnvɔɪs/", meaning:"청구서; 청구하다"},
  {word:"involve", pronunciation:"/ɪnˈvɒlv/", meaning:"포함하다, 관련시키다"},
  {word:"issue", pronunciation:"/ˈɪʃuː/", meaning:"발행하다; 문제"},
  // J (추가)
  {word:"job", pronunciation:"/dʒɒb/", meaning:"직업, 업무"},
  {word:"joint", pronunciation:"/dʒɔɪnt/", meaning:"공동의; 합작"},
  {word:"justify", pronunciation:"/ˈdʒʌstɪfaɪ/", meaning:"정당화하다"},
  // L (추가)
  {word:"launch", pronunciation:"/lɔːntʃ/", meaning:"시작하다; 출시"},
  {word:"lease", pronunciation:"/liːs/", meaning:"임대차; 임대하다"},
  {word:"legal", pronunciation:"/ˈliːɡəl/", meaning:"법적인, 합법적인"},
  {word:"leverage", pronunciation:"/ˈlevərɪdʒ/", meaning:"활용하다; 레버리지"},
  {word:"liability", pronunciation:"/ˌlaɪəˈbɪlɪti/", meaning:"부채; 책임"},
  {word:"logistics", pronunciation:"/ləˈdʒɪstɪks/", meaning:"물류, 병참"},
  {word:"loyal", pronunciation:"/ˈlɔɪəl/", meaning:"충성스러운"},
  // M (추가)
  {word:"maintain", pronunciation:"/meɪnˈteɪn/", meaning:"유지하다, 관리하다"},
  {word:"manage", pronunciation:"/ˈmænɪdʒ/", meaning:"관리하다, 처리하다"},
  {word:"margin", pronunciation:"/ˈmɑːrdʒɪn/", meaning:"이윤; 여백"},
  {word:"measure", pronunciation:"/ˈmeʒər/", meaning:"측정하다; 조치"},
  {word:"mediate", pronunciation:"/ˈmiːdieɪt/", meaning:"중재하다"},
  {word:"merge", pronunciation:"/mɜːrdʒ/", meaning:"합병하다, 병합하다"},
  {word:"milestone", pronunciation:"/ˈmaɪlstoʊn/", meaning:"이정표, 중요한 사건"},
  {word:"minimum", pronunciation:"/ˈmɪnɪməm/", meaning:"최소; 최소의"},
  {word:"monitor", pronunciation:"/ˈmɒnɪtər/", meaning:"감시하다; 모니터"},
  {word:"mutual", pronunciation:"/ˈmjuːtʃuəl/", meaning:"상호간의, 공동의"},
  // N (추가)
  {word:"negotiate", pronunciation:"/nɪˈɡoʊʃieɪt/", meaning:"협상하다"},
  {word:"network", pronunciation:"/ˈnetwɜːrk/", meaning:"네트워크; 인맥"},
  {word:"notify", pronunciation:"/ˈnoʊtɪfaɪ/", meaning:"알리다, 통지하다"},
  // O (추가)
  {word:"objective", pronunciation:"/əbˈdʒektɪv/", meaning:"목표; 객관적인"},
  {word:"obligation", pronunciation:"/ˌɒblɪˈɡeɪʃən/", meaning:"의무, 책임"},
  {word:"obtain", pronunciation:"/əbˈteɪn/", meaning:"획득하다, 얻다"},
  {word:"occupy", pronunciation:"/ˈɒkjəpaɪ/", meaning:"차지하다, 점유하다"},
  {word:"operate", pronunciation:"/ˈɒpəreɪt/", meaning:"운영하다, 작동하다"},
  {word:"optimize", pronunciation:"/ˈɒptɪmaɪz/", meaning:"최적화하다"},
  {word:"option", pronunciation:"/ˈɒpʃən/", meaning:"선택권, 옵션"},
  {word:"outcome", pronunciation:"/ˈaʊtkʌm/", meaning:"결과, 성과"},
  {word:"outline", pronunciation:"/ˈaʊtlaɪn/", meaning:"개요; 윤곽을 잡다"},
  {word:"outsource", pronunciation:"/ˈaʊtsɔːrs/", meaning:"외주를 주다"},
  {word:"overall", pronunciation:"/ˌoʊvərˈɔːl/", meaning:"전반적인; 전체적으로"},
  {word:"overcome", pronunciation:"/ˌoʊvərˈkʌm/", meaning:"극복하다"},
  {word:"overhead", pronunciation:"/ˈoʊvərhed/", meaning:"간접비; 머리 위의"},
  // P (추가)
  {word:"partnership", pronunciation:"/ˈpɑːrtnərʃɪp/", meaning:"동반자 관계, 제휴"},
  {word:"patent", pronunciation:"/ˈpeɪtənt/", meaning:"특허; 특허의"},
  {word:"penalty", pronunciation:"/ˈpenəlti/", meaning:"벌칙, 위약금"},
  {word:"percent", pronunciation:"/pərˈsent/", meaning:"퍼센트, 백분율"},
  {word:"perform", pronunciation:"/pərˈfɔːrm/", meaning:"수행하다, 실행하다"},
  {word:"permit", pronunciation:"/pərˈmɪt/", meaning:"허가하다; 허가증"},
  {word:"phase", pronunciation:"/feɪz/", meaning:"단계; 단계적으로 실행하다"},
  {word:"policy", pronunciation:"/ˈpɒləsi/", meaning:"정책, 방침"},
  {word:"portfolio", pronunciation:"/pɔːrtˈfoʊlioʊ/", meaning:"포트폴리오, 투자 종목"},
  {word:"potential", pronunciation:"/pəˈtenʃəl/", meaning:"잠재력; 잠재적인"},
  {word:"practical", pronunciation:"/ˈpræktɪkəl/", meaning:"실용적인, 실제적인"},
  {word:"present", pronunciation:"/prɪˈzent/", meaning:"제시하다; 현재의"},
  {word:"priority", pronunciation:"/praɪˈɒrɪti/", meaning:"우선순위"},
  {word:"process", pronunciation:"/ˈprɒses/", meaning:"과정; 처리하다"},
  {word:"procure", pronunciation:"/prəˈkjʊər/", meaning:"조달하다, 획득하다"},
  {word:"productive", pronunciation:"/prəˈdʌktɪv/", meaning:"생산적인"},
  {word:"profit", pronunciation:"/ˈprɒfɪt/", meaning:"이익, 수익"},
  {word:"promote", pronunciation:"/prəˈmoʊt/", meaning:"촉진하다; 승진시키다"},
  {word:"proposal", pronunciation:"/prəˈpoʊzəl/", meaning:"제안서, 제안"},
  {word:"prospective", pronunciation:"/prəˈspektɪv/", meaning:"예비의, 장래의"},
  // Q (추가)
  {word:"qualify", pronunciation:"/ˈkwɒlɪfaɪ/", meaning:"자격을 갖추다"},
  // R (추가)
  {word:"reach", pronunciation:"/riːtʃ/", meaning:"달성하다; 범위"},
  {word:"rebound", pronunciation:"/rɪˈbaʊnd/", meaning:"반등하다; 반등"},
  {word:"recognize", pronunciation:"/ˈrekəɡnaɪz/", meaning:"인식하다, 인정하다"},
  {word:"record", pronunciation:"/rɪˈkɔːrd/", meaning:"기록하다; 기록"},
  {word:"recover", pronunciation:"/rɪˈkʌvər/", meaning:"회복하다"},
  {word:"recruit", pronunciation:"/rɪˈkruːt/", meaning:"채용하다; 신입 직원"},
  {word:"reduce", pronunciation:"/rɪˈdjuːs/", meaning:"줄이다, 감소시키다"},
  {word:"regulate", pronunciation:"/ˈreɡjəleɪt/", meaning:"규제하다, 조정하다"},
  {word:"release", pronunciation:"/rɪˈliːs/", meaning:"공개하다; 출시"},
  {word:"remedy", pronunciation:"/ˈremədi/", meaning:"개선하다; 해결책"},
  {word:"renew", pronunciation:"/rɪˈnjuː/", meaning:"갱신하다, 재개하다"},
  {word:"replace", pronunciation:"/rɪˈpleɪs/", meaning:"교체하다, 대체하다"},
  {word:"require", pronunciation:"/rɪˈkwaɪər/", meaning:"요구하다, 필요로 하다"},
  {word:"reserve", pronunciation:"/rɪˈzɜːrv/", meaning:"예약하다; 비축"},
  {word:"resolve", pronunciation:"/rɪˈzɒlv/", meaning:"해결하다, 결의하다"},
  {word:"resource", pronunciation:"/rɪˈzɔːrs/", meaning:"자원, 재원"},
  {word:"revenue", pronunciation:"/ˈrevənjuː/", meaning:"수입, 매출"},
  {word:"review", pronunciation:"/rɪˈvjuː/", meaning:"검토하다; 검토"},
  {word:"revise", pronunciation:"/rɪˈvaɪz/", meaning:"수정하다, 개정하다"},
  {word:"reward", pronunciation:"/rɪˈwɔːrd/", meaning:"보상하다; 보상"},
  {word:"risk", pronunciation:"/rɪsk/", meaning:"위험; 위험을 감수하다"},
  {word:"role", pronunciation:"/roʊl/", meaning:"역할"},
  // S (추가)
  {word:"secure", pronunciation:"/sɪˈkjʊər/", meaning:"확보하다; 안전한"},
  {word:"select", pronunciation:"/sɪˈlekt/", meaning:"선택하다"},
  {word:"sensitive", pronunciation:"/ˈsensɪtɪv/", meaning:"민감한"},
  {word:"serve", pronunciation:"/sɜːrv/", meaning:"제공하다, 봉사하다"},
  {word:"shift", pronunciation:"/ʃɪft/", meaning:"이동하다; 교대 근무"},
  {word:"significant", pronunciation:"/sɪɡˈnɪfɪkənt/", meaning:"중요한, 상당한"},
  {word:"solution", pronunciation:"/səˈluːʃən/", meaning:"해결책, 해법"},
  {word:"source", pronunciation:"/sɔːrs/", meaning:"출처; 조달하다"},
  {word:"stabilize", pronunciation:"/ˈsteɪbɪlaɪz/", meaning:"안정시키다"},
  {word:"statement", pronunciation:"/ˈsteɪtmənt/", meaning:"진술; 명세서"},
  {word:"strategy", pronunciation:"/ˈstrætədʒi/", meaning:"전략"},
  {word:"structure", pronunciation:"/ˈstrʌktʃər/", meaning:"구조; 조직하다"},
  {word:"submit", pronunciation:"/səbˈmɪt/", meaning:"제출하다"},
  {word:"substitute", pronunciation:"/ˈsʌbstɪtjuːt/", meaning:"대체하다; 대리인"},
  {word:"sufficient", pronunciation:"/səˈfɪʃənt/", meaning:"충분한"},
  {word:"support", pronunciation:"/səˈpɔːrt/", meaning:"지원하다; 지원"},
  {word:"survey", pronunciation:"/ˈsɜːrveɪ/", meaning:"조사하다; 설문"},
  // T (추가)
  {word:"target", pronunciation:"/ˈtɑːrɡɪt/", meaning:"목표; 목표로 하다"},
  {word:"terminate", pronunciation:"/ˈtɜːrmɪneɪt/", meaning:"종료하다, 해고하다"},
  {word:"transfer", pronunciation:"/ˈtrænsfɜːr/", meaning:"이전하다; 이체"},
  {word:"transparency", pronunciation:"/trænsˈpærənsi/", meaning:"투명성"},
  {word:"trend", pronunciation:"/trend/", meaning:"추세, 경향"},
  // U (추가)
  {word:"undertake", pronunciation:"/ˌʌndərˈteɪk/", meaning:"착수하다, 맡다"},
  {word:"utilize", pronunciation:"/ˈjuːtɪlaɪz/", meaning:"활용하다, 이용하다"},
  // V (추가)
  {word:"validate", pronunciation:"/ˈvælɪdeɪt/", meaning:"검증하다, 유효화하다"},
  {word:"value", pronunciation:"/ˈvæljuː/", meaning:"가치; 중요시하다"},
  {word:"verify", pronunciation:"/ˈverɪfaɪ/", meaning:"확인하다, 검증하다"},
  {word:"vision", pronunciation:"/ˈvɪʒən/", meaning:"비전, 전망"},
  // W (추가)
  {word:"withdraw", pronunciation:"/wɪðˈdrɔː/", meaning:"철회하다, 인출하다"},
  // Y
  {word:"yield", pronunciation:"/jiːld/", meaning:"산출량; 양보하다, 생산하다"},
];
