/* ─────────────────────────────────────────────────────
   CONSTANTS.JS — 디자인 토큰, 카테고리, 헬퍼, 단어장
───────────────────────────────────────────────────── */

// ── Design Tokens ──────────────────────────────────
export const T = {
  bg:        "#F7F4EF",
  bgCard:    "#FFFFFF",
  bgSub:     "#F0EDE7",
  border:    "#E4DDD3",
  borderMid: "#CEC5B8",
  text:      "#2C2825",
  textSub:   "#8C8077",
  textMute:  "#B8AFA5",
  accent:    "#6B7C3A",
};

// ── Categories ─────────────────────────────────────
export const CATS = [
  { id:"schedule", label:"일정",    icon:"o", color:"#C0443A", bg:"#FDECEA", text:"#9B2E25" },
  { id:"event",    label:"이벤트",  icon:"o", color:"#B09520", bg:"#FBF8E3", text:"#7A6A10" },
  { id:"archive",  label:"아카이브", icon:"o", color:"#4A8A5A", bg:"#EBF5EE", text:"#2E6640" },
];

export const ARCHIVE_SUBS = [
  { id:"health",  label:"건강", color:"#4A8A5A", bg:"#EBF5EE", text:"#2E6640" },  // 초록
  { id:"economy", label:"경제", color:"#2E6FA5", bg:"#E8F2FA", text:"#1A4E7A" },  // 파랑
  { id:"review",  label:"리뷰", color:"#1A4080", bg:"#E5EAF5", text:"#0F2A60" },  // 남색
  { id:"etc",     label:"기타", color:"#7E4FA0", bg:"#F3EBF8", text:"#5A2E80" },  // 보라
];

export const HEALTH_SUBS = [
  { id:"weight",          label:"체중" },
  { id:"diet",            label:"식단" },
  { id:"weight_training", label:"웨이트" },
  { id:"cardio",          label:"카디오" },
];

export const REVIEW_SUBS = [
  { id:"book",   label:"책" },
  { id:"wine",   label:"와인" },
  { id:"coffee", label:"커피" },
];

// ── View constants ──────────────────────────────────
export const VIEWS     = ["주","월","년"];
export const WEEKDAYS  = ["일","월","화","수","목","금","토"];
export const MONTHS_KR = ["1월","2월","3월","4월","5월","6월","7월","8월","9월","10월","11월","12월"];
export const HOURS     = Array.from({length:24},(_,i)=>i);

// ── Today (module load time) ────────────────────────
export const today = new Date();

// ── Helper functions ────────────────────────────────
/** 로컬 타임존 기준 YYYY-MM-DD 문자열 */
export const dateStr = (d) =>
  `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;

const _HEALTH_SUBS = ["weight","diet","weight_training","cardio"];
const _REVIEW_SUBS = ["book","wine","coffee"];

/** 카테고리/서브카테고리로 색상 객체 반환 */
export const allCatOf = (category, sub_category) => {
  if (category === "archive") {
    if (!sub_category) return CATS.find(c=>c.id==="archive") || CATS[0];
    // 개별 서브를 상위 그룹으로 매핑
    if (_HEALTH_SUBS.includes(sub_category)) return ARCHIVE_SUBS.find(s=>s.id==="health")  || CATS[2];
    if (_REVIEW_SUBS.includes(sub_category)) return ARCHIVE_SUBS.find(s=>s.id==="review")  || CATS[2];
    if (sub_category === "economy")          return ARCHIVE_SUBS.find(s=>s.id==="economy") || CATS[2];
    // 직접 매치 (health, economy, review, etc)
    return ARCHIVE_SUBS.find(s=>s.id===sub_category) || CATS.find(c=>c.id==="archive") || CATS[0];
  }
  return CATS.find(c=>c.id===category) || CATS[0];
};
export const catOf = (category, sub) => allCatOf(category, sub);

/** 해당 날짜가 속한 주의 7일 배열 (일~토) */
export function getWeekDays(date) {
  const d = new Date(date), day = d.getDay();
  return Array.from({length:7}, (_, i) => {
    const x = new Date(d);
    x.setDate(x.getDate() - day + i);
    return x;
  });
}

/** 월 캘린더 셀 배열 (앞 빈칸 null, 날짜 Date 객체) */
export function getMonthCells(date) {
  const year = date.getFullYear(), month = date.getMonth();
  const first = new Date(year, month, 1);
  const last  = new Date(year, month + 1, 0);
  const cells = [];
  for (let i = 0; i < first.getDay(); i++) cells.push(null);
  for (let d = 1; d <= last.getDate(); d++) cells.push(new Date(year, month, d));
  return cells;
}

// ── Word Bank (500개) ───────────────────────────────
export const TOEIC_WORDS = [
  // A
  {word:"abandon",        meaning:"포기하다, 버리다"},
  {word:"accelerate",     meaning:"가속하다, 촉진하다"},
  {word:"accommodate",    meaning:"수용하다, 편의를 제공하다"},
  {word:"accomplish",     meaning:"성취하다, 완수하다"},
  {word:"accurate",       meaning:"정확한, 정밀한"},
  {word:"acquire",        meaning:"획득하다, 습득하다"},
  {word:"adjacent",       meaning:"인접한, 근접한"},
  {word:"adjustment",     meaning:"조정, 수정"},
  {word:"agenda",         meaning:"의제, 안건"},
  {word:"allocate",       meaning:"할당하다, 배분하다"},
  {word:"amend",          meaning:"수정하다, 개정하다"},
  {word:"analyze",        meaning:"분석하다"},
  {word:"anticipate",     meaning:"예상하다, 기대하다"},
  {word:"apparent",       meaning:"명백한, 외견상의"},
  {word:"applicable",     meaning:"적용 가능한, 해당되는"},
  {word:"appoint",        meaning:"임명하다, 지정하다"},
  {word:"appreciate",     meaning:"감사하다, 가치를 인정하다"},
  {word:"appropriate",    meaning:"적절한, 알맞은"},
  {word:"approximately",  meaning:"대략, 약"},
  {word:"assess",         meaning:"평가하다, 산정하다"},
  {word:"assign",         meaning:"할당하다, 배정하다"},
  {word:"audit",          meaning:"감사; 감사하다"},
  {word:"authorize",      meaning:"승인하다, 권한을 부여하다"},
  {word:"available",      meaning:"이용 가능한, 구할 수 있는"},
  // B
  {word:"benchmark",      meaning:"기준, 척도; 기준으로 삼다"},
  {word:"beneficial",     meaning:"유익한, 이로운"},
  {word:"board",          meaning:"이사회; 탑승하다"},
  {word:"brief",          meaning:"간단한; 요약하다"},
  {word:"budget",         meaning:"예산; 예산을 세우다"},
  // C
  {word:"calculate",      meaning:"계산하다, 추정하다"},
  {word:"candidate",      meaning:"후보자, 지원자"},
  {word:"capacity",       meaning:"수용력, 능력, 용량"},
  {word:"category",       meaning:"범주, 분류"},
  {word:"circulate",      meaning:"순환하다, 배포하다"},
  {word:"clarify",        meaning:"명확히 하다, 설명하다"},
  {word:"collaborate",    meaning:"협력하다, 공동 작업하다"},
  {word:"compile",        meaning:"편집하다, 수집하다"},
  {word:"comply",         meaning:"따르다, 준수하다"},
  {word:"comprehensive",  meaning:"포괄적인, 종합적인"},
  {word:"concentrate",    meaning:"집중하다, 농축하다"},
  {word:"confirm",        meaning:"확인하다, 확정하다"},
  {word:"considerable",   meaning:"상당한, 중요한"},
  {word:"consistently",   meaning:"일관되게, 꾸준히"},
  {word:"contract",       meaning:"계약(서); 계약을 맺다"},
  {word:"contribute",     meaning:"기여하다, 공헌하다"},
  {word:"convenient",     meaning:"편리한, 간편한"},
  {word:"coordinate",     meaning:"조율하다, 조정하다"},
  {word:"corporate",      meaning:"기업의, 법인의"},
  {word:"correspond",     meaning:"일치하다, 서신 왕래하다"},
  {word:"credential",     meaning:"자격증, 신임장"},
  {word:"currently",      meaning:"현재, 지금"},
  // D
  {word:"deadline",       meaning:"마감일, 기한"},
  {word:"decrease",       meaning:"감소하다, 줄다; 감소"},
  {word:"delegate",       meaning:"위임하다; 대표, 대리인"},
  {word:"demonstrate",    meaning:"증명하다, 시연하다"},
  {word:"determine",      meaning:"결정하다, 판단하다"},
  {word:"develop",        meaning:"개발하다, 발전시키다"},
  {word:"dispatch",       meaning:"발송하다; 급파"},
  {word:"diverse",        meaning:"다양한, 여러 종류의"},
  {word:"document",       meaning:"문서; 기록하다"},
  {word:"draft",          meaning:"초안; 초안을 작성하다"},
  // E
  {word:"efficient",      meaning:"효율적인, 능률적인"},
  {word:"eligible",       meaning:"자격이 있는, 적합한"},
  {word:"emphasize",      meaning:"강조하다, 역설하다"},
  {word:"enable",         meaning:"가능하게 하다, 허용하다"},
  {word:"enhance",        meaning:"향상시키다, 높이다"},
  {word:"ensure",         meaning:"보장하다, 확실히 하다"},
  {word:"establish",      meaning:"설립하다, 확립하다"},
  {word:"evaluate",       meaning:"평가하다, 검토하다"},
  {word:"exceed",         meaning:"초과하다, 능가하다"},
  {word:"expedite",       meaning:"촉진하다, 신속히 처리하다"},
  {word:"expand",         meaning:"확장하다, 늘리다"},
  {word:"expertise",      meaning:"전문 지식, 전문성"},
  // F
  {word:"facilitate",     meaning:"용이하게 하다, 촉진하다"},
  {word:"feasible",       meaning:"실현 가능한, 타당한"},
  {word:"finalize",       meaning:"마무리하다, 확정하다"},
  {word:"flexible",       meaning:"유연한, 융통성 있는"},
  {word:"forecast",       meaning:"예측하다; 예보, 전망"},
  {word:"formulate",      meaning:"공식화하다, 수립하다"},
  {word:"fundamental",    meaning:"기본적인, 근본적인"},
  // G
  {word:"generate",       meaning:"생성하다, 일으키다"},
  {word:"genuine",        meaning:"진짜의, 진정한"},
  {word:"guarantee",      meaning:"보장하다; 보증"},
  {word:"guideline",      meaning:"지침, 가이드라인"},
  // H
  {word:"highlight",      meaning:"강조하다; 하이라이트"},
  // I
  {word:"identify",       meaning:"확인하다, 파악하다"},
  {word:"implement",      meaning:"실행하다, 이행하다"},
  {word:"improve",        meaning:"개선하다, 향상시키다"},
  {word:"indicate",       meaning:"나타내다, 표시하다"},
  {word:"initiative",     meaning:"주도권, 계획, 솔선수범"},
  {word:"integrate",      meaning:"통합하다, 합치다"},
  {word:"inventory",      meaning:"재고, 목록"},
  {word:"investigate",    meaning:"조사하다, 수사하다"},
  // M
  {word:"maintain",       meaning:"유지하다, 관리하다"},
  {word:"mandatory",      meaning:"의무적인, 필수의"},
  {word:"manufacture",    meaning:"제조하다; 제조업"},
  {word:"maximize",       meaning:"극대화하다, 최대화하다"},
  {word:"mediate",        meaning:"중재하다, 조정하다"},
  {word:"monitor",        meaning:"감시하다, 관리하다; 모니터"},
  {word:"motivate",       meaning:"동기를 부여하다"},
  // N
  {word:"negotiate",      meaning:"협상하다, 교섭하다"},
  // O
  {word:"objective",      meaning:"목표, 목적; 객관적인"},
  {word:"obtain",         meaning:"얻다, 획득하다"},
  {word:"operate",        meaning:"운영하다, 작동하다"},
  {word:"optimize",       meaning:"최적화하다"},
  {word:"organize",       meaning:"조직하다, 정리하다"},
  {word:"outline",        meaning:"윤곽, 개요; 개략적으로 서술하다"},
  {word:"oversee",        meaning:"감독하다, 지휘하다"},
  // P
  {word:"participate",    meaning:"참가하다, 참여하다"},
  {word:"perform",        meaning:"수행하다, 공연하다"},
  {word:"potential",      meaning:"잠재적인; 가능성, 잠재력"},
  {word:"priority",       meaning:"우선순위, 최우선 사항"},
  {word:"procedure",      meaning:"절차, 과정"},
  {word:"productivity",   meaning:"생산성, 생산력"},
  {word:"promote",        meaning:"촉진하다, 승진시키다"},
  {word:"proposal",       meaning:"제안, 제의"},
  // Q
  {word:"qualify",        meaning:"자격을 갖추다, 적합하다"},
  // R
  {word:"recommend",      meaning:"추천하다, 권장하다"},
  {word:"recruit",        meaning:"채용하다; 신입, 신병"},
  {word:"relevant",       meaning:"관련된, 적절한"},
  {word:"require",        meaning:"필요로 하다, 요구하다"},
  {word:"resolve",        meaning:"해결하다, 결의하다"},
  {word:"revenue",        meaning:"수익, 수입"},
  {word:"revise",         meaning:"수정하다, 개정하다"},
  // S
  {word:"schedule",       meaning:"일정; 계획하다, 예정하다"},
  {word:"significant",    meaning:"중요한, 상당한"},
  {word:"strategy",       meaning:"전략, 방략"},
  {word:"submit",         meaning:"제출하다, 굴복하다"},
  {word:"sufficient",     meaning:"충분한, 족한"},
  {word:"supervise",      meaning:"감독하다, 지도하다"},
  {word:"sustainable",    meaning:"지속 가능한"},
  // T
  {word:"terminate",      meaning:"종료하다, 해고하다"},
  {word:"thoroughly",     meaning:"철저히, 완전히"},
  {word:"transfer",       meaning:"이전하다, 옮기다; 이전"},
  {word:"transparent",    meaning:"투명한, 명백한"},
  // U
  {word:"utilize",        meaning:"활용하다, 이용하다"},
  // V
  {word:"validate",       meaning:"검증하다, 유효화하다"},
  {word:"verify",         meaning:"확인하다, 검증하다"},
  {word:"viable",         meaning:"실행 가능한, 생존 가능한"},
  // ── 추가 단어 (201~500) ──────────────────────────
  {word:"abide",          meaning:"준수하다, 지키다"},
  {word:"abolish",        meaning:"폐지하다, 없애다"},
  {word:"absorb",         meaning:"흡수하다, 받아들이다"},
  {word:"abstract",       meaning:"추상적인; 요약, 추출하다"},
  {word:"accountable",    meaning:"책임이 있는"},
  {word:"accrue",         meaning:"누적되다, 생기다"},
  {word:"acknowledge",    meaning:"인정하다, 감사를 표하다"},
  {word:"adapt",          meaning:"적응하다, 개조하다"},
  {word:"adequate",       meaning:"충분한, 적절한"},
  {word:"adhere",         meaning:"고수하다, 부착하다"},
  {word:"adjacent",       meaning:"인접한"},
  {word:"administer",     meaning:"관리하다, 집행하다"},
  {word:"adopt",          meaning:"채택하다, 입양하다"},
  {word:"advance",        meaning:"진전, 발전; 나아가다"},
  {word:"adversely",      meaning:"불리하게, 역으로"},
  {word:"affiliate",      meaning:"제휴하다; 계열사"},
  {word:"affirm",         meaning:"확언하다, 지지하다"},
  {word:"aggregate",      meaning:"합계, 집합체; 합산하다"},
  {word:"agile",          meaning:"민첩한, 기민한"},
  {word:"alleviate",      meaning:"완화하다, 경감하다"},
  {word:"alternate",      meaning:"교대하다; 대안의"},
  {word:"ambiguous",      meaning:"모호한, 불분명한"},
  {word:"amortize",       meaning:"상각하다, 할부 상환하다"},
  {word:"amplify",        meaning:"증폭하다, 확대하다"},
  {word:"annually",       meaning:"연간으로, 해마다"},
  {word:"appeal",         meaning:"매력; 호소하다, 항소하다"},
  {word:"appraisal",      meaning:"평가, 감정"},
  {word:"arbitrate",      meaning:"중재하다"},
  {word:"archives",       meaning:"기록 보관소, 문서 보관"},
  {word:"articulate",     meaning:"명확히 표현하다; 명확한"},
  {word:"aspect",         meaning:"측면, 양상"},
  {word:"assemble",       meaning:"조립하다, 모이다"},
  {word:"attrition",      meaning:"감소, 마모, 자연 감원"},
  {word:"authentic",      meaning:"진정한, 진본의"},
  {word:"automate",       meaning:"자동화하다"},
  {word:"backup",         meaning:"백업; 지원, 후원"},
  {word:"bandwidth",      meaning:"대역폭, 처리 용량"},
  {word:"bilateral",      meaning:"양자 간의, 쌍방의"},
  {word:"binding",        meaning:"구속력 있는; 제본"},
  {word:"boost",          meaning:"높이다, 향상시키다; 증가"},
  {word:"bottleneck",     meaning:"병목 현상"},
  {word:"breach",         meaning:"위반; 침해하다"},
  {word:"bulk",           meaning:"대량의; 대부분"},
  {word:"calibrate",      meaning:"조정하다, 검정하다"},
  {word:"campaign",       meaning:"캠페인, 운동"},
  {word:"capital",        meaning:"자본, 수도; 대문자"},
  {word:"carrier",        meaning:"운반업자, 항공사"},
  {word:"clarification",  meaning:"명확화, 해명"},
  {word:"clause",         meaning:"절, 조항"},
  {word:"client",         meaning:"고객, 의뢰인"},
  {word:"closure",        meaning:"폐쇄, 마감"},
  {word:"collateral",     meaning:"담보; 부수적인"},
  {word:"commence",       meaning:"시작하다, 개시하다"},
  {word:"commission",     meaning:"수수료, 위원회; 위임하다"},
  {word:"commitment",     meaning:"헌신, 약속, 의지"},
  {word:"commodity",      meaning:"상품, 원자재"},
  {word:"compensation",   meaning:"보상, 급여, 보수"},
  {word:"competency",     meaning:"역량, 능력"},
  {word:"competitive",    meaning:"경쟁적인, 경쟁력 있는"},
  {word:"concise",        meaning:"간결한, 명료한"},
  {word:"confidential",   meaning:"기밀의, 비밀의"},
  {word:"configure",      meaning:"구성하다, 설정하다"},
  {word:"consult",        meaning:"상담하다, 참고하다"},
  {word:"contingency",    meaning:"비상사태, 우발 상황"},
  {word:"conversion",     meaning:"전환, 변환"},
  {word:"convey",         meaning:"전달하다, 운반하다"},
  {word:"cooperate",      meaning:"협력하다, 협조하다"},
  {word:"crucial",        meaning:"결정적인, 중요한"},
  {word:"customary",      meaning:"관례적인, 습관적인"},
  {word:"database",       meaning:"데이터베이스"},
  {word:"debrief",        meaning:"보고를 받다; 사후 보고"},
  {word:"default",        meaning:"채무 불이행; 기본값"},
  {word:"defer",          meaning:"미루다, 연기하다"},
  {word:"deficit",        meaning:"적자, 부족분"},
  {word:"deploy",         meaning:"배치하다, 전개하다"},
  {word:"depreciate",     meaning:"가치가 떨어지다, 감가상각하다"},
  {word:"designate",      meaning:"지정하다, 임명하다"},
  {word:"devote",         meaning:"헌신하다, 바치다"},
  {word:"differentiator", meaning:"차별화 요소"},
  {word:"diligent",       meaning:"부지런한, 성실한"},
  {word:"disclose",       meaning:"공개하다, 밝히다"},
  {word:"discount",       meaning:"할인; 할인하다"},
  {word:"discrepancy",    meaning:"불일치, 차이"},
  {word:"distribute",     meaning:"배포하다, 분배하다"},
  {word:"diversify",      meaning:"다각화하다, 다양화하다"},
  {word:"dividend",       meaning:"배당금"},
  {word:"domain",         meaning:"영역, 도메인"},
  {word:"downturn",       meaning:"경기 침체, 하락"},
  {word:"duplicate",      meaning:"복제하다, 중복하다; 복사본"},
  {word:"durable",        meaning:"내구성 있는, 오래가는"},
  {word:"effective",      meaning:"효과적인, 시행 중인"},
  {word:"eliminate",      meaning:"제거하다, 없애다"},
  {word:"embark",         meaning:"시작하다, 착수하다"},
  {word:"emerge",         meaning:"나타나다, 부상하다"},
  {word:"endorse",        meaning:"지지하다, 보증하다"},
  {word:"enforce",        meaning:"시행하다, 집행하다"},
  {word:"engagement",     meaning:"참여, 약속, 교전"},
  {word:"enterprise",     meaning:"기업, 사업; 진취적 기상"},
  {word:"equivalent",     meaning:"동등한, 상당하는"},
  {word:"estimate",       meaning:"추정하다; 견적"},
  {word:"execute",        meaning:"실행하다, 집행하다"},
  {word:"exempt",         meaning:"면제하다; 면제된"},
  {word:"exert",          meaning:"발휘하다, 행사하다"},
  {word:"expenditure",    meaning:"지출, 비용"},
  {word:"explicit",       meaning:"명시적인, 분명한"},
  {word:"extract",        meaning:"추출하다; 발췌"},
  {word:"feedback",       meaning:"피드백, 의견"},
  {word:"fiscal",         meaning:"재정의, 회계의"},
  {word:"fluctuate",      meaning:"변동하다, 오르내리다"},
  {word:"follow-up",      meaning:"후속 조치; 추가적인"},
  {word:"framework",      meaning:"틀, 체계, 구조"},
  {word:"freight",        meaning:"화물, 운송료"},
  {word:"fulfill",        meaning:"이행하다, 충족시키다"},
  {word:"function",       meaning:"기능; 작동하다"},
  {word:"gain",           meaning:"얻다, 증가하다; 이익"},
  {word:"govern",         meaning:"통치하다, 지배하다"},
  {word:"gradual",        meaning:"점진적인"},
  {word:"grant",          meaning:"승인하다, 수여하다; 보조금"},
  {word:"gross",          meaning:"총, 전체의; 역겨운"},
  {word:"handle",         meaning:"처리하다, 다루다"},
  {word:"headquarters",   meaning:"본사, 본부"},
  {word:"hierarchical",   meaning:"계층적인"},
  {word:"hire",           meaning:"고용하다; 임금"},
  {word:"incentive",      meaning:"장려책, 유인"},
  {word:"inclusive",      meaning:"포괄적인, 모두 포함하는"},
  {word:"incremental",    meaning:"점진적인, 증분의"},
  {word:"indispensable",  meaning:"없어서는 안 될, 필수적인"},
  {word:"inform",         meaning:"알리다, 통보하다"},
  {word:"infrastructure", meaning:"기반시설, 인프라"},
  {word:"innovation",     meaning:"혁신, 쇄신"},
  {word:"inspect",        meaning:"검사하다, 점검하다"},
  {word:"installment",    meaning:"할부, 분납"},
  {word:"instruct",       meaning:"지시하다, 가르치다"},
  {word:"interim",        meaning:"임시의, 중간의"},
  {word:"invoice",        meaning:"청구서, 송장"},
  {word:"iterate",        meaning:"반복하다, 되풀이하다"},
  {word:"joint",          meaning:"공동의, 합동의; 관절"},
  {word:"jurisdiction",   meaning:"관할권, 사법권"},
  {word:"justify",        meaning:"정당화하다, 옹호하다"},
  {word:"launch",         meaning:"출시하다, 시작하다; 발사"},
  {word:"layoff",         meaning:"일시 해고, 정리해고"},
  {word:"lease",          meaning:"임대하다; 임대차 계약"},
  {word:"ledger",         meaning:"장부, 원장"},
  {word:"leverage",       meaning:"지렛대 효과; 활용하다"},
  {word:"liability",      meaning:"부채, 법적 책임"},
  {word:"liaison",        meaning:"연락 담당자, 연계"},
  {word:"liquidity",      meaning:"유동성, 현금 유동성"},
  {word:"logistics",      meaning:"물류, 병참"},
  {word:"lump sum",       meaning:"일시불, 일괄 지급"},
  {word:"mandate",        meaning:"위임하다; 명령, 위임"},
  {word:"margin",         meaning:"이윤, 여백, 차이"},
  {word:"maturity",       meaning:"성숙, 만기"},
  {word:"mediation",      meaning:"중재, 조정"},
  {word:"memorandum",     meaning:"각서, 메모"},
  {word:"merge",          meaning:"합병하다, 병합하다"},
  {word:"methodology",    meaning:"방법론"},
  {word:"milestone",      meaning:"이정표, 중요한 단계"},
  {word:"minimize",       meaning:"최소화하다"},
  {word:"mitigate",       meaning:"완화하다, 경감하다"},
  {word:"modify",         meaning:"수정하다, 변경하다"},
  {word:"mutual",         meaning:"상호의, 공동의"},
  {word:"notify",         meaning:"통보하다, 알리다"},
  {word:"objective",      meaning:"목표; 객관적인"},
  {word:"obligation",     meaning:"의무, 채무"},
  {word:"offset",         meaning:"상쇄하다; 보상"},
  {word:"ongoing",        meaning:"진행 중인, 계속되는"},
  {word:"onset",          meaning:"시작, 발생"},
  {word:"operational",    meaning:"운영의, 작동 중인"},
  {word:"outperform",     meaning:"능가하다, 더 좋은 성과를 내다"},
  {word:"outsource",      meaning:"외주 주다, 아웃소싱하다"},
  {word:"overhead",       meaning:"간접비, 경상비"},
  {word:"overdue",        meaning:"기한이 지난, 오래 끈"},
  {word:"payroll",        meaning:"급여 명단, 급여 지급"},
  {word:"penalize",       meaning:"벌주다, 불이익을 주다"},
  {word:"pension",        meaning:"연금"},
  {word:"perceive",       meaning:"인식하다, 지각하다"},
  {word:"periodic",       meaning:"주기적인, 정기적인"},
  {word:"persistent",     meaning:"끈질긴, 지속적인"},
  {word:"pivotal",        meaning:"중추적인, 결정적인"},
  {word:"platform",       meaning:"플랫폼, 발판"},
  {word:"portfolio",      meaning:"포트폴리오, 서류 가방"},
  {word:"preliminary",    meaning:"예비의, 준비의"},
  {word:"procurement",    meaning:"조달, 구매"},
  {word:"proficient",     meaning:"능숙한, 숙련된"},
  {word:"prohibit",       meaning:"금지하다"},
  {word:"projection",     meaning:"예측, 전망, 투영"},
  {word:"proofread",      meaning:"교정하다"},
  {word:"prototype",      meaning:"원형, 시제품"},
  {word:"provision",      meaning:"조항, 규정; 공급"},
  {word:"proximity",      meaning:"근접성, 인접"},
  {word:"pursue",         meaning:"추구하다, 쫓다"},
  {word:"quantify",       meaning:"정량화하다"},
  {word:"query",          meaning:"질문; 질의하다"},
  {word:"quota",          meaning:"할당량, 쿼터"},
  {word:"ratify",         meaning:"비준하다, 승인하다"},
  {word:"reallocation",   meaning:"재배분, 재할당"},
  {word:"receipt",        meaning:"영수증, 수령"},
  {word:"refund",         meaning:"환불; 환불하다"},
  {word:"reimburse",      meaning:"상환하다, 변제하다"},
  {word:"relocate",       meaning:"이전하다, 이동하다"},
  {word:"remittance",     meaning:"송금, 입금"},
  {word:"replenish",      meaning:"보충하다, 다시 채우다"},
  {word:"report",         meaning:"보고하다; 보고서"},
  {word:"represent",      meaning:"대표하다, 나타내다"},
  {word:"reschedule",     meaning:"일정을 변경하다"},
  {word:"restrict",       meaning:"제한하다, 규제하다"},
  {word:"retain",         meaning:"유지하다, 보유하다"},
  {word:"retrospective",  meaning:"소급적인; 회고"},
  {word:"scalable",       meaning:"확장 가능한"},
  {word:"scrutinize",     meaning:"면밀히 검토하다"},
  {word:"sector",         meaning:"분야, 부문"},
  {word:"segment",        meaning:"구분하다; 구분, 세그먼트"},
  {word:"sequential",     meaning:"순차적인"},
  {word:"settlement",     meaning:"해결, 정산, 결제"},
  {word:"shareholder",    meaning:"주주"},
  {word:"shortage",       meaning:"부족, 결핍"},
  {word:"simulate",       meaning:"모의 실험하다, 모방하다"},
  {word:"solicitation",   meaning:"권유, 청원"},
  {word:"specification",  meaning:"명세서, 사양"},
  {word:"stakeholder",    meaning:"이해관계자"},
  {word:"standardize",    meaning:"표준화하다"},
  {word:"statute",        meaning:"법령, 규정"},
  {word:"streamline",     meaning:"간소화하다, 효율화하다"},
  {word:"subsidize",      meaning:"보조금을 주다"},
  {word:"successively",   meaning:"연속해서, 잇달아"},
  {word:"succession",     meaning:"연속, 승계"},
  {word:"surplus",        meaning:"잉여, 흑자"},
  {word:"suspend",        meaning:"중단하다, 정지시키다"},
  {word:"synergy",        meaning:"시너지, 상승효과"},
  {word:"tariff",         meaning:"관세, 요금표"},
  {word:"taskforce",      meaning:"특별팀, 태스크포스"},
  {word:"technical",      meaning:"기술적인, 전문적인"},
  {word:"tenure",         meaning:"재직 기간, 임기"},
  {word:"threshold",      meaning:"임계값, 한계점"},
  {word:"timeline",       meaning:"일정표, 연대표"},
  {word:"transaction",    meaning:"거래, 처리"},
  {word:"transition",     meaning:"전환, 이행"},
  {word:"turnover",       meaning:"이직률, 매출액"},
  {word:"unanimous",      meaning:"만장일치의"},
  {word:"undermine",      meaning:"약화시키다, 훼손하다"},
  {word:"uniform",        meaning:"균일한, 통일된; 제복"},
  {word:"update",         meaning:"업데이트하다; 최신 정보"},
  {word:"upgrade",        meaning:"업그레이드하다, 향상시키다"},
  {word:"urgency",        meaning:"긴급함, 시급성"},
  {word:"vacancy",        meaning:"공석, 빈자리"},
  {word:"variance",       meaning:"차이, 변동"},
  {word:"vendor",         meaning:"판매자, 공급업체"},
  {word:"venture",        meaning:"모험; 벤처 사업"},
  {word:"versatile",      meaning:"다재다능한, 다용도의"},
  {word:"vested",         meaning:"기득권이 있는, 확정된"},
  {word:"visibility",     meaning:"가시성, 인지도"},
  {word:"vital",          meaning:"필수적인, 생명의"},
  {word:"volume",         meaning:"양, 용량, 권"},
  {word:"vulnerability",  meaning:"취약성, 약점"},
  {word:"waive",          meaning:"포기하다, 면제하다"},
  {word:"wholesale",      meaning:"도매; 대규모의"},
  {word:"workforce",      meaning:"노동력, 인력"},
  {word:"workload",       meaning:"업무량, 작업 부하"},
  {word:"benchmark",      meaning:"기준점; 성과를 측정하다"},
  {word:"coherent",       meaning:"일관된, 논리적인"},
  {word:"concession",     meaning:"양보, 특허권"},
  {word:"consolidate",    meaning:"통합하다, 강화하다"},
  {word:"contingent",     meaning:"우발적인; 조건부"},
  {word:"convene",        meaning:"소집하다, 소환하다"},
  {word:"deter",          meaning:"단념시키다, 억제하다"},
  {word:"discretion",     meaning:"재량권, 분별력"},
  {word:"disposition",    meaning:"처분, 성향"},
  {word:"downsize",       meaning:"규모를 축소하다"},
  {word:"equity",         meaning:"지분, 자기 자본; 공정"},
  {word:"escalate",       meaning:"단계적으로 높아지다"},
  {word:"exemplary",      meaning:"모범적인"},
  {word:"expose",         meaning:"노출시키다, 드러내다"},
  {word:"fluctuation",    meaning:"변동, 파동"},
  {word:"forthcoming",    meaning:"곧 있을, 다가오는"},
  {word:"franchise",      meaning:"프랜차이즈; 선거권"},
  {word:"gauge",          meaning:"측정하다; 계기"},
  {word:"ground",         meaning:"근거; 기반으로 하다"},
  {word:"initiative",     meaning:"주도권, 계획"},
  {word:"intangible",     meaning:"무형의, 눈에 보이지 않는"},
  {word:"integral",       meaning:"필수적인, 완전한"},
  {word:"interim",        meaning:"중간의, 임시의"},
  {word:"intrinsic",      meaning:"본질적인, 고유한"},
  {word:"lapse",          meaning:"경과, 실수; 실효되다"},
  {word:"lucrative",      meaning:"수익성이 좋은"},
  {word:"meticulous",     meaning:"꼼꼼한, 세심한"},
  {word:"nominal",        meaning:"명목상의, 미미한"},
  {word:"obsolete",       meaning:"구식의, 더 이상 쓸모없는"},
  {word:"paramount",      meaning:"가장 중요한, 최고의"},
  {word:"parity",         meaning:"동등, 균형"},
  {word:"perpetual",      meaning:"영구적인, 지속적인"},
  {word:"preliminary",    meaning:"예비의, 준비의"},
  {word:"premise",        meaning:"전제; 구내"},
  {word:"proactive",      meaning:"능동적인, 사전 예방적인"},
  {word:"proficiency",    meaning:"능숙함, 유창함"},
  {word:"proprietary",    meaning:"소유권의, 독점적인"},
  {word:"reconcile",      meaning:"조화시키다, 화해시키다"},
  {word:"redundancy",     meaning:"중복, 잉여, 정리해고"},
  {word:"reinforce",      meaning:"강화하다, 보강하다"},
  {word:"remunerate",     meaning:"보수를 주다"},
  {word:"replicate",      meaning:"복제하다, 반복하다"},
  {word:"resilient",      meaning:"회복력 있는, 탄력적인"},
  {word:"restructure",    meaning:"구조 조정하다"},
  {word:"rigorous",       meaning:"엄격한, 철저한"},
  {word:"robust",         meaning:"강건한, 견고한"},
  {word:"sanction",       meaning:"제재; 승인하다"},
  {word:"scrutiny",       meaning:"면밀한 검토, 조사"},
  {word:"seamless",       meaning:"원활한, 매끄러운"},
  {word:"solicitation",   meaning:"권유, 청원"},
  {word:"stringent",      meaning:"엄격한, 까다로운"},
  {word:"subordinate",    meaning:"부하, 하위의"},
  {word:"substantial",    meaning:"상당한, 실질적인"},
  {word:"systematic",     meaning:"체계적인, 조직적인"},
  {word:"tactical",       meaning:"전술적인"},
  {word:"tangible",       meaning:"유형의, 실제적인"},
  {word:"transparent",    meaning:"투명한, 솔직한"},
  {word:"turnaround",     meaning:"방향 전환, 회복"},
  {word:"unilateral",     meaning:"일방적인"},
  {word:"unprecedented",  meaning:"전례 없는"},
  {word:"viable",         meaning:"실행 가능한"},
  {word:"warranty",       meaning:"보증, 품질 보증"},
  {word:"yield",          meaning:"산출량; 양보하다, 생산하다"},
  // ── 추가 단어 ────────────────────────────────────
  {word:"accelerate",     meaning:"가속화하다"},
  {word:"acclimate",      meaning:"적응하다"},
  {word:"accumulate",     meaning:"축적하다, 모으다"},
  {word:"adjourn",        meaning:"휴회하다, 연기하다"},
  {word:"adjunct",        meaning:"부가물, 보조"},
  {word:"advent",         meaning:"도래, 출현"},
  {word:"advocacy",       meaning:"지지, 옹호"},
  {word:"aggregate",      meaning:"합계, 총액"},
  {word:"allocation",     meaning:"배분, 할당"},
  {word:"annotation",     meaning:"주석, 메모"},
  {word:"arbitration",    meaning:"중재, 조정"},
  {word:"asset",          meaning:"자산, 재산"},
  {word:"assumption",     meaning:"가정, 전제"},
  {word:"attain",         meaning:"달성하다, 이루다"},
  {word:"audit",          meaning:"감사; 감사하다"},
  {word:"benchmark",      meaning:"기준; 비교 평가하다"},
  {word:"bond",           meaning:"채권; 유대, 결합"},
  {word:"brainstorm",     meaning:"브레인스토밍하다"},
  {word:"breakeven",      meaning:"손익 분기점"},
  {word:"calibrate",      meaning:"보정하다, 맞추다"},
  {word:"cascade",        meaning:"연속 효과; 흘러내리다"},
  {word:"catalyst",       meaning:"촉매, 촉진제"},
  {word:"certify",        meaning:"증명하다, 인증하다"},
  {word:"charter",        meaning:"설립 허가서; 전세하다"},
  {word:"co-author",      meaning:"공동 저자"},
  {word:"collaborate",    meaning:"공동 작업하다"},
  {word:"commodity",      meaning:"상품, 일용품"},
  {word:"concur",         meaning:"동의하다, 일치하다"},
  {word:"confiscate",     meaning:"몰수하다, 압수하다"},
  {word:"consortium",     meaning:"컨소시엄, 협회"},
  {word:"contingency",    meaning:"우발 상황"},
  {word:"copyright",      meaning:"저작권"},
  {word:"deadline",       meaning:"마감 기한"},
  {word:"deficit",        meaning:"결손, 부족"},
  {word:"depreciation",   meaning:"감가상각, 가치 하락"},
  {word:"derivative",     meaning:"파생 상품; 파생된"},
  {word:"endorse",        meaning:"서명하다, 보증하다"},
  {word:"execute",        meaning:"실행하다, 처형하다"},
  {word:"exhaustive",     meaning:"철저한, 완전한"},
  {word:"feasibility",    meaning:"타당성, 실현 가능성"},
];
  
